### ISSUE TITLE
Chore Request: Bump to scipy >= 1.6

### ISSUE THREAD

**Issue by aptlin** [evidentlyai/evidently#100]
Is there any reason to stay on ~1.5?
https://github.com/evidentlyai/evidently/blob/94e4c84ff3c6147d7a5364650fa20e01bb4a7b69/requirements.txt#L8

**Comment by aptlin** [comment]
Scipy 1.6 added an option to compute one-sided p-values, which is valuable for a lot of companies. Because of the restriction above, I cannot just add evidently as a dev dependency using `poetry add -D`, but would love to!

**Comment by Liraim** [comment]
Hi @aptlin,
Probably we can relax version constrain to `scipy>=1.5.4` so you can use over version.
We will check it, and fix it in next release.

**Comment by Liraim** [comment]
Hi again,
We merged changes for this in new release 0.1.39.dev0. You can now try it out!

**Comment by emeli-dral** [comment]
Hi @aptlin, this is working now.
Thanks again for bringing this up!
