### ISSUE TITLE
Feature Request: Allow array of confidence scores to be passed in to match features.

### ISSUE THREAD

**Issue by yodanater** [evidentlyai/evidently#103]
Current design only allows one confidence score as an option. Would be nice to allow an array of confidence scores so each feature could be evaluated differently. 
Thanks for any consideration on this.

**Comment by Liraim** [comment]
Hi @yodanater ,

We are planning to include such feature in next release.

**Comment by Liraim** [comment]
Hi again,

We added this in new release 0.1.39.dev0. You can found example of that in https://github.com/evidentlyai/evidently/blob/main/evidently/examples/california_housing_drift_with_options.ipynb
