### ISSUE TITLE
Weird labelling for y-axis in some error plots

### ISSUE THREAD

**Issue by jlopezpena** [evidentlyai/evidently#1030]
In a regression test report (using default preset) I noticed some weird labelling in the error plots for the negative part of the axis (see screenshot), with ticks labelled eg `"â^'0.3"` instead of `-0.3`

![image](https://github.com/evidentlyai/evidently/assets/3518950/ef66ffa7-5dd9-4534-a0d2-9433a98c520f)

**Comment by GwenVCX** [comment]
Hi @emeli-dral and @elenasamuylova,

I have created a fix for this in https://github.com/evidentlyai/evidently/pull/1183 with the following with the following result:

**Currrent State**
<img width="476" alt="current_state" src="https://github.com/evidentlyai/evidently/assets/54825049/25df40a8-432f-4e88-8d99-dfeaee69403f">

**After Fix**
<img width="475" alt="after_fix" src="https://github.com/evidentlyai/evidently/assets/54825049/3c393d9f-b756-4a97-b9ad-21c9682f6e4c">

Please review and merge if it's ok.

Cheers, 

Gwen

**Comment by GwenVCX** [comment]
Hi @jlopezpena,

I am experiencing the same problem and have proposed a fix in https://github.com/evidentlyai/evidently/pull/1183. In the meantime, if you want a quick fix, you can add the following code around the output code:

**Before the given code**
`
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="utf8">
      </head>
      <body>
`

**After the given code**
`</html>`
