### ISSUE TITLE
 Support for using embeded images instead of Plotly interactive component

### ISSUE THREAD

**Issue by 2qU24Tlb** [evidentlyai/evidently#1046]
Out reports contain multiple large datasets. In general we can do sampling but for a few of them we want to keep all data. The size of the final report html is around 100MB which cause the browser crashed. So I wonder if it's possible to have an option to generate reports with static images instead of Plotly figures.

**Comment by elenasamuylova** [comment]
Hi @2qU24Tlb, 

Which Evidently version are you using? (Pre-0.3.2, all visualizations retained raw data. Currently, they are aggregated by default).

It is not possible to swap Plotly, but you can get the Report output as JSON and optionally include the render data https://docs.evidentlyai.com/user-guide/customization/json-dict-output#include-render, and then visualize it elsewhere using a different tool.

If you are using a Preset (e.g. ClassificationPreset), you can also experiment with creating a custom Report instead and including only some of the metrics – if not all of them are required.

**Comment by 2qU24Tlb** [comment]
Hi @elenasamuylova ,
We are using latest version of Evidently. 
I will try your suggestions. Thank you very much.
