### ISSUE TITLE
What are you guys using for dependency management?

### ISSUE THREAD

**Issue by bhattbhuwan13** [evidentlyai/evidently#106]
I can see that you have wisely separated your dependencies into `requirements.txt` and `dev-requirements.txt`. Which tool are you using to separate those dependencies? Is it `poetry`?

**Comment by Liraim** [comment]
Hi @bhattbhuwan13 ,
For now we are doing this manually, because adding new dependencies isn't happen often.
And we are looking for better alternative (`poetry` + `pip compile` is one of them).
