### ISSUE TITLE
Missing "Per feature"-metrics in Regression

### ISSUE THREAD

**Issue by DonnyWhoLovedBowling** [evidentlyai/evidently#1075]
Somehow I can't replicatete full regression performance report as it is shown on: https://docs.evidentlyai.com/presets/reg-performance

All the "per-feature" analyses plots seem to be missing (components 10-12 in the above link)

I ran this notebook (as a norml python-script): https://github.com/evidentlyai/community-examples/blob/main/tutorials/bicycle_demand_monitoring_setup.ipynb 

And still all the "per-feature" components seem to be missing. I don't see any warnings or errors occurring and I updated evidently to several versions, including the latest (0.4.19) , so currently I am a bit in the dark on what's going on. 

Thanks in advance!

Edit: by debugging/digging in the evidently code I found that the problem was that the option "render.raw_data" needed to be set to True. I've got the plots I want, but it might be a good idea to document this somewhere or explain in the tutorials section why this is necessary.

**Comment by elenasamuylova** [comment]
Hi @DonnyWhoLovedBowling,

You found the correct solution, this visualization requires passing the raw data option. 

```
report = Report(
    metrics=[
      ClassificationQualityByFeatureTable(),
    ],
    options={"render": {"raw_data": True}}
  )
report.run(reference_data=ref, current_data=cur)
report
```

It is in the backlog to re-implement this metric to support the non-aggregated visualization. (Either this or the documentation update is coming soon :) You are also welcome to submit a PR to the docs to add a note about this!

**Comment by DonnyWhoLovedBowling** [comment]
Hi @elenasamuylova,

thanks for your quick reply! I just noticed that if you search your website on "raw data", you actually find the right documentation (https://docs.evidentlyai.com/user-guide/customization/report-data-aggregation#non-aggregated-plots-for-reports)

Perhaps it might be an easy solution just to place a link to this page at places where it is relevant. For example: https://docs.evidentlyai.com/presets/reg-performance 
Or it might be nice for completeness/overview to add a mention in this table for each metric where it is relevant? https://docs.evidentlyai.com/reference/all-metrics

For now I'm closing this issue, thanks again.
