### ISSUE TITLE
How to set a different threshold for classification probability tab that is not 0.5?

### ISSUE THREAD

**Issue by Guidosalimbeni** [evidentlyai/evidently#109]
I am having issues to understand how to use  ProbClassificationPerformanceTab() as it seems the position of the item in the list column_mapping.prediction is very important to the output of the recall precision curve and area under the curve.  

On the other hand, the classification report that comes in the same dashboard seems to use a default 0,5 threshold to cut the probability predictions. Is there a way to change the threshold?

also is there a way to set what to consider as the positive class in the precision recall curve?

thanks

**Comment by emeli-dral** [comment]
Hi @Guidosalimbeni 

Yes, you are right, for this report class order matters. In particular, column order in Probabilistic Binary Classification. The tool expects that the target (so-called positive) class is the first in the column_mapping['prediction'] list.
Unfortunately, now we do not have an option to set a positive class explicitly, but it is definitely needed. Thank you for pointing it out.

At the moment there is no way to set a custom threshold for the probability predictions, but it will be added in the next release. We are adding ```QualityMetricOptions``` and the threshold will be there.

**Comment by 0lgaF** [comment]
Hi @Guidosalimbeni 

We added this functionality in #122 
You can get more details here https://docs.evidentlyai.com/user-guide/customization/options-for-quality-metrics
