### ISSUE TITLE
Keyword Error

### ISSUE THREAD

**Issue by achandras1597** [evidentlyai/evidently#11]
facing object 'dashboard' is not J-Son serializable

**Comment by emeli-dral** [comment]
Hi! Yes, the Dashboard object is not JSON serialisable by default and we did not implement specific method to dump it is as a JSON yet. But we are considering this direction though!

Are you trying to do something like:
```
import json
dashboard_json = json.dumps(dashboard)
```
?
Could you please tell us more about the end problem you are truing to solve? We might be able to suggest something.

**Comment by emeli-dral** [comment]
Hey @achandras1597!
Despite the fact that we do not have a specific method to dump dashboard as a nice JSON file, we implemented a quick solution for you.

We implemented methods ‘_json()’ and ‘_save_to_json(path)’ for Dashboard class. Current implementation dumps the whole Dashboard data into the JSON, which is probably way too much! :) But these methods are already available (you will need to update the package), so you can give it a try.

This is an example of the JSON generation:
```
drift_report = Dashboard(reference_frame, current_frame, column_mapping = None, tabs=[DriftTab])
drift_report._json()
``` 
And  an example of the saving JSON file:
```
drift_report = Dashboard(reference_frame, current_frame, column_mapping = None, tabs=[DriftTab])
drift_report._save_to_json('filename.json')
``` 
Also, we added —output_type parameter for terminal mode, so now you can choose ‘json’ option there as well:
```
python -m evidently analyze --config config.json --reference reference.csv  --current current.csv --output_path save_report_here --output_type json
```
Hope, this will help!
