### ISSUE TITLE
Add a new `ExactMatch` descriptor to Evidently

### ISSUE THREAD

**Issue by elenasamuylova** [evidentlyai/evidently#1312]
# Add an `ExactMatch()` Descriptor

About Hacktoberfest contributions: https://github.com/evidentlyai/evidently/wiki/Hacktoberfest-2024

**Description:**

The `ExactMatch()` descriptor will compare text between two columns and return `True` if the text in both columns matches exactly, and `False` otherwise.

It should accept `with_column` parameter similar to `SemanticSimilarity` descriptor.

**Comment by oceanthunder** [comment]
Hi @elenasamuylova, I'm interested in working on this issue to add an ExactMatch() Descriptor. Could I be assigned to this task? I'm eager to contribute but still learning, so any guidance or resources you could provide would be greatly appreciated. Thank you!

**Comment by gagan-bhullar-tech** [comment]
@elenasamuylova please review PR.

**Comment by elenasamuylova** [comment]
Hi @oceanthunder, since we already got a PR for this descriptor, we'd review it first. You are welcome to start working on other issues: just leave a comment for others that you are working on it.

**Comment by oceanthunder** [comment]
@elenasamuylova sure, thanks!
