### ISSUE TITLE
Add new `JSONSchemaMatch()` descriptor to Evidently

### ISSUE THREAD

**Issue by elenasamuylova** [evidentlyai/evidently#1314]
About Hacktoberfest contributions: https://github.com/evidentlyai/evidently/wiki/Hacktoberfest-2024

**Description:**

Add the `JSONSchemaMatch()` descriptor that will evaluate whether a returned text is a JSON object with a schema that matches a structure specified by the user.  Implement two different matching options.

Minimal match:
* Checks if the JSON includes the listed keys.
* The values associated with these keys must not be `None`.
* Optionally, the descriptor can validate the types of the values for each key (e.g., name: string), as specified by the user.

Exact match (option):
* Ensures that the JSON contains only the provided keys, with no extra or missing keys.
* Validates both the presence and types of keys if specified by the user.

Returns True or False fo JSON schema match.

If the JSON is invalid, the schema can never match.

**Comment by yashaswikakumanu** [comment]
@elenasamuylova  I would like to work on this , please assign this to me

**Comment by elenasamuylova** [comment]
Hi @yashaswikakumanu, we don't formally assign issues, but you are very welcome to work on it!
