### ISSUE TITLE
Add a new `IsValidPython` descriptor to Evidently

### ISSUE THREAD

**Issue by elenasamuylova** [evidentlyai/evidently#1320]
About Hacktoberfest contributions: https://github.com/evidentlyai/evidently/wiki/Hacktoberfest-2024

**Description**

Add the `IsValidPython()` descriptor that checks whether the text in a specified column contains valid Python code. This descriptor returns `True` for valid Python code that does not contain syntax errors and `False` for invalid code.

**Comment by karthikk1006** [comment]
Hey! I'm new to LLMs and ML. I'm really interested in being a part of hacktoberfest. Could you pls assign this to me. I'll learn and try to do something with this. If there's something similar of even doc work do let me know and assign it to me. Thanks in advance

**Comment by elenasamuylova** [comment]
Hi @karthikk1006, we do not formally assign the issues, but you are very welcome to start working on it! Thanks for considering to contribute 🚀

**Comment by ramachaitanya0** [comment]
Hi @elenasamuylova , do we need to extract the python code from text and test the python code has syntax errors or not ?
