### ISSUE TITLE
Need more examples about how to use user own statistical tests function.

### ISSUE THREAD

**Issue by KevinRyu** [evidentlyai/evidently#143]
Hi.

I want to use own statistical tests function with evidently dashboard.
I added my function to stattest_func argument in DataDriftOptions.
I got an error but solving is not easy for me. I don't know the correct usage.
So, I tried to find detail docs or example but I couldn't.

Can I have some guide?

**Comment by Liraim** [comment]
Hi @KevinRyu,
Can you provide the error you got there?

Statistical test function should meet several requirements:
- signature `(reference_data: pd.Series, current_data: pd.Series) -> float`
- return value in range from 0.0 to 1.0
Here an example with custom stattest function [examples/how_to_questions/drift_dashboard_with_options_california_housing.ipynb ](https://github.com/evidentlyai/evidently/blob/main/examples/how_to_questions/drift_dashboard_with_options_california_housing.ipynb)

**Comment by KevinRyu** [comment]
Hi.

Thanks a lot. I got off work today.
I will check and give you feedback.

2022년 2월 8일 (화) 오후 6:58, Vyacheslav Morov ***@***.***>님이 작성:

**Comment by emeli-dral** [comment]
We implemented many statistical tests, here is a full list of available tests: https://docs.evidentlyai.com/user-guide/customization/options-for-statistical-tests May be on of them will suit straight away.

And here is an example of the custom stat test usage: https://github.com/evidentlyai/evidently/blob/main/examples/how_to_questions/drift_dashboard_with_options_california_housing.ipynb
