### ISSUE TITLE
Grafana dashboard detect data drift even though both reference and production data are same

### ISSUE THREAD

**Issue by alokrajg** [evidentlyai/evidently#171]
I was experimenting with Evidently's Real-time ML monitoring with Grafana and getting data drift detection even though when both reference and production datasets are exactly same (production data is just the copy of reference data).

**Please find the below example:**
![image](https://user-images.githubusercontent.com/24756965/155931962-c088b5f7-5961-4f67-9518-302431af98d4.png)

Here is the preview of **Reference data**
![image](https://user-images.githubusercontent.com/24756965/155932292-2c1db483-3fca-4133-abb5-5863ddb0e1a2.png)

Here is the preview of **Production data**
![image](https://user-images.githubusercontent.com/24756965/155932150-dbdb63a7-ad23-4b68-aaa8-04bef79030d2.png)

**Comment by Tapot** [comment]
Hello, thank you for the question.

Looks like the drift depends on data window size and season changes in Bike dataset.

I'm going to check the case with the same reference and production/current datasets and will come back with more details and explanations.

**Comment by alokrajg** [comment]
Hello @Tapot,
Thanks for the reply 👍
Actually, everything is working fine when I am using the default Bike Dataset. But when I replace this data with other datasets (for example this [Weather Data](https://www.kaggle.com/budincsevity/szeged-weather)), I am facing the data drift issue when both reference and production/current datasets are same.

**Comment by 0lgaF** [comment]
Hi @alokrajg! 

I think that we really met the drift here. Weather data have strong seasonality, so the piece of the dataset can differ significantly from the whole data.

<img width="200" alt="image" src="https://user-images.githubusercontent.com/36808731/159704402-00bab01b-00d7-4944-be44-da831f03c26f.png">

<img width="220" alt="image" src="https://user-images.githubusercontent.com/36808731/159704647-e7adf0ef-8624-4bf6-8dac-48c8a60c22f0.png">

<img width="677" alt="image" src="https://user-images.githubusercontent.com/36808731/159704953-260aa1d5-bbc9-4f23-b46c-00022de65e8f.png">

**Comment by alokrajg** [comment]
Hi @0lgaF,
Thanks for the nice explanation :blush:
Now I got the reason for the data drift.
