### ISSUE TITLE
grafana_monitoring_service does not work

### ISSUE THREAD

**Issue by Amirshirazi-tech** [evidentlyai/evidently#174]
Hi Evidenty team, I tried to use the example for real time monitoring and I went through your explanation. I had all three files that you mentioned in step 4, but  there was no pre-built Grafana dashboard, and Prometheus was empty.  I waited for a while, but nothing happened. Would you please let me know what the problem is? Thanks.

**Comment by emeli-dral** [comment]
Hi @Amirshirazi-tech,
Thank you for opening the issue.

We believe the reason might be in the order of the services starting. We performed some test internally and figured out that sometimes Prometheus and Grafana starts before Evidently service. In this scenario service often cannot connect to Prometheus and send data there.  We now work to create a script that will simplify the example run (and fix the order of services launching).

Currently, I can suggest launching services in the right order manually. I mean, first launch evidently service (docker compose up evidently_service), then launch Prometheus and finally Grafana the same way. Hopefully, it should help.

**Comment by Amirshirazi-tech** [comment]
Hi @emeli-dral,
Thank you  for your response. I did, but nothing happened. Even I started from beginning and went step by step, but I had the same issue. The Evidently service works, but Prometheus and Grafana not.

**Comment by emeli-dral** [comment]
Hi @Amirshirazi-tech ,
I just wanted to mention that we reworked the example of the grafana integration heavily and automated a lot of launching steps.
I believe it worth try now (if it is still relevant of course :) ), hopefully the example should work straight away.
