### ISSUE TITLE
How to monitor multiple models using grafana

### ISSUE THREAD

**Issue by debimishra89** [evidentlyai/evidently#188]
Hi, 
I have multiple models in my project and want to monitor all on grafana.
but I am unable to do so. 
The below link doesn't tell how to setup multiple model monitoring.

> https://github.com/evidentlyai/evidently/tree/main/examples/integrations/grafana_monitoring_service

Is there any other document/guide I can make use of

**Comment by Tapot** [comment]
Hi!

The current example implements a separate application logic for sending data to Prometheus and then on to Grafana for one model.

We have not a guide for this case yet(.

If you want to monitor multiple models, you can change `MonitoringService` and add separate labels for each model and filters for Grafana dashboards by the labels.

Can you describe what case do you want to implement  - different Grafana dashboards for each model, compare models both other? If we better understand the issue, maybe we can add a guide for it or update the current example.

**Comment by debimishra89** [comment]
@Tapot , Thanks for responding!
Let me tell you in a simpler way
Currently you are providing 3 dashboards for grafana- regression, classification and data drift.

let's say I have 2 regression models to monitor. how can I create 2 regression dashboards.
I am not able to find a way to create multiple dashbords.

**Comment by emeli-dral** [comment]
Hi @debimishra89!

I know it's been a while, but we recently released an example that does exactly what you describe. You can try out the updated example here: https://github.com/evidentlyai/evidently/tree/main/examples/integrations/grafana_monitoring_service
