### ISSUE TITLE
Distribution plots of prediction score for binary classifiers

### ISSUE THREAD

**Issue by joaomario-brainly** [evidentlyai/evidently#19]
Hi would be nice to extend the binary classifier probabilistic report to include distribution plots (in addition to the scatter plot) of the prediction score grouped by the positive/negative true class. This way it will help identify the right cut-off point.
For the multi-label problem we can do multiple plots using 1-vs-all modeling.

**Comment by emeli-dral** [comment]
Hi @joaomario-brainly,
We are about to add this visualization to our newest update release. Was wondering if that is something you meant? Let us know your thoughts! 

<img width="786" alt="probability_distr_plot" src="https://user-images.githubusercontent.com/22995068/115554681-6872c900-a2b7-11eb-9864-33fddb53f854.png">

**Comment by joaomario-brainly** [comment]
That would be awesome yes.
If you can also have a kde interpolation you could measure the overlapping between the two curves which is the area where there are FP and FN.

Thanks. You are doing an amazing work.
