### ISSUE TITLE
Different JSON format when generating json in Docker container

### ISSUE THREAD

**Issue by sandeeps311** [evidentlyai/evidently#205]
Profile(sections=[DataDriftProfileSection()]) generating different json on windows system and in docker container.
Please see below samples
**Windows JSON:**
"metrics": {
                "n_features": 4,
                "n_drifted_features": 4,
                "share_drifted_features": 1.0,
                "dataset_drift": true,
                "TestFeature": {
                    "current_small_hist": [[], []],
                    "ref_small_hist": [[], []],
                    "feature_type": "num",
                    "p_value": 3.3406466154230965e-07
                },

**Docker JSON:**:
"metrics": 
{"n_features": 4, 
"n_drifted_features": 4, 
"share_drifted_features": 1.0, 
"dataset_drift": true, 
"ViewOfProjectManagementCode":
 {"current_small_hist": [[], []], 
"ref_small_hist": [[], []], 
"feature_type": "num", 
"stattest_name": "K-S p_value", 
"drift_score": 7.954740392478146e-09
},

Please verify p_values replaced by K-S p_values
and drift score added

**Comment by Liraim** [comment]
Hi,  @PoweredAutomation ,

looks like you have different version of library on windows and inside container.
In v0.1.48.dev0 we have changed output of Json profile.

You can check version of library by:
```python
import evidently

print(evidently.__version__)
```
