### ISSUE TITLE
stattests not available for categorical features

### ISSUE THREAD

**Issue by BrunoRoth95** [evidentlyai/evidently#225]
Hello all,

I'm trying to run the data drift dashboard on my dataset which is composed only by categorical features but I'm getting the following error when selecting one of the following stattests ["psi", "z", "jensenshannon", "kl_div"]:

`StatTestInvalidFeatureTypeError: Stattest psi isn't applicable to feature of type cat. Available feature types: ['num']`

This is weird, because I was following the [adult dataset](https://github.com/evidentlyai/evidently/blob/main/examples/how_to_questions/stat_test_specification_for_data_drift_adult.ipynb) example and they seem to use those stattests in their categorical features. Are they not available anymore?

**Comment by Liraim** [comment]
Hi @BrunoRoth95 ,
Can you check what version of evidently package are you using?
PSI support for categorical features was introduced in 0.1.49.dev0.

**Comment by BrunoRoth95** [comment]
Hi @Liraim ,
Thank you for your message. Indeed I was using an older version. Now it is working correctly :)
