### ISSUE TITLE
Unable to view the dashboard on Jupyter notebook.

### ISSUE THREAD

**Issue by vikrant-sahu** [evidentlyai/evidently#25]
I am trying to generate the data drift report on jupyter notebook but it shows just loading and no graphs like it's showing in your examples notebooks. However I can write it to HTML file and see the report.

So does this requires any package or setting changes?

**Comment by emeli-dral** [comment]
Hi @vikrant-sahu !
Thanks for opening up the issue.  

We are trying to reproduce the bug.
Can you please share a bit more data:
- version of evidently package
- your operating system
- how you generate the reports - via ipython, Jupyter, Jupyter Lab

Just to check: make sure you had nbextention installed before using the tool to generate reports in the notebook:
$ jupyter nbextension install --sys-prefix --symlink --overwrite --py evidently
$ jupyter nbextension enable evidently --py --sys-prefix

**Comment by aakash-dusane** [comment]
> Hi @vikrant-sahu !
> Thanks for opening up the issue.
> 
> We are trying to reproduce the bug.
> Can you please share a bit more data:
> 
> * version of evidently package
> * your operating system
> * how you generate the reports - via ipython, Jupyter, Jupyter Lab
> 
> Just to check: make sure you had nbextention installed before using the tool to generate reports in the notebook:
> $ jupyter nbextension install --sys-prefix --symlink --overwrite --py evidently
> $ jupyter nbextension enable evidently --py --sys-prefix

@emeli-dral Thanks for sharing. This solution worked for me!

**Comment by emeli-dral** [comment]
Happy this has helped!

Also, we made UI compatible with Google Collab; you might like to create some Dashboards there.
Here are some examples of Probabilistic Classification Performance Dashboard: [Iris](https://colab.research.google.com/drive/1uFN0ZWNLk3ExylBywq_M8oGkmac0lDrq), 
[Breast Cancer](https://colab.research.google.com/drive/1vwEBgGnDVk5BJG2PXT1w41VfZ-_bq_Sw)

**Comment by shrinandj** [comment]
FWIW, I installed evidently and the nbextension (both the commands mentioned above) and restarted the jupyter notebook. The dashboards still didn't show up.

Package version installed: 0.1.42.dev0
OS: Mac OSX
Tool used: Jupyter Lab

**Comment by emeli-dral** [comment]
@shrinandj, thank you for letting us know!

Quick thought: using ```dashboard.show(mode='inline')``` could help to display the dashboard. This mode uses an alternative mechanism to render HTML and does not depend on ```nbextension```. 

@Tapot, could you please help to figure this out? Whether or not inline mode works, the ```nbextension``` is also supposed to work (especially for mac os 🤷‍♀️).

**Comment by bingblackbean** [comment]
> Hi @shrinandj ,
> 
> for Pylab **inline** should work fine, we checked this internally. Could you please try to specify mode like this: `dashboard.show(mode='inline')` and check if it works for you?
> 
> Nbextention does not work for pylab. We created separate issue #123 to explore labextension aswell.

dashboard.show(mode='inline') works for me.  thanks for saving the day.
env:
Jupyter lab desktop
