### ISSUE TITLE
Conda version way behind Pip

### ISSUE THREAD

**Issue by seanyboi** [evidentlyai/evidently#250]
Current version on anaconda is: 0.1.23.dev0 way behind 0.1.50

**Comment by Liraim** [comment]
Hi @seanyboi ,
As far as I'm aware of we do not upload version to Anaconda on regular basis.

I'll check what version is there (maybe it was one of tests of upload).

Does your work require for library be available in Anaconda or Pypi is enough?

**Comment by seanyboi** [comment]
PyPi is definitely enough, but I know a lot of data scientists / machine learning engineer who use anaconda especially with the new MacBook M1's so if you can it would be nice! :)

**Comment by emeli-dral** [comment]
Added to the backlog.
Conda support will start from the stable release.
