### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by pplonski** [evidentlyai/evidently#251]
Do you have some explanations how drift is detected? For example what statistical test is used for which data type?  I can't find it in the docs. Thanks!

**Comment by elenasamuylova** [comment]
Hi @pplonski! Here is the relevant section of the docs: https://docs.evidentlyai.com/reports/data-drift#how-it-works. There is a default logic that picks a statistical test based on feature type, the number of unique values, and the number of observations. You can also modify it by choosing a different test or adding your own.

**Comment by pplonski** [comment]
Thank you!
