### ISSUE TITLE
Custom stattest Profile (DataDriftProfileSection(), CatTargetDriftProfileSection())

### ISSUE THREAD

**Issue by Omega8800** [evidentlyai/evidently#258]
Hi,

I would like to request some help in changing the statistical tests used in DataDriftProfileSection(), CatTargetDriftProfileSection() on a numerical/categorical level.

Here is what I have so far:

```
# Initialization 
column_mapping = ColumnMapping()
column_mapping.task = "classification"
column_mapping.target = "target"
column_mapping.prediction = None
column.mapping.id = "id"
column_mapping.datetime = "date"

column_mapping.numerical_features = ["N1", "N2", "N3"]
column_mapping.categorical_features = ["C1", "C2", "C3"]

# Calculation
data_drift_profile = Profile(sections=[DataDriftProfileSection(), CatDriftProfileSection()])
data_drift_profile.calculate(historical, last_quarter, column_mapping=column_mapping)
```
How can I apply a specific metric inside each Profile() section for numerical and categorical variables?

I viewed the following "Options for Statistical Tests" but am unable to incorporate this into the Profile() section:

https://github.com/evidentlyai/evidently/blob/main/docs/book/customization/options-for-statistical-tests.md

**Comment by Tapot** [comment]
Hi!

Thank you for the question.

If I understand your question correctly, you want to apply different stattests for num and cat features with JSON profile.

You can do it with `options` parameter for `Profile` like:

```
drift_options = DataDriftOptions(
        cat_features_stattest="kl_div",
        num_features_stattest="ks"
  )
my_profile = Profile(
      sections=[DataDriftProfileSection(), CatTargetDriftProfileSection(), NumTargetDriftProfileSection()],
      options=[drift_options]
 )

my_profile.calculate(
      reference_data=reference_data, current_data=current_data, column_mapping=data_mapping
)
```

Let me know If I've missed something in the question and your case!

**Comment by Omega8800** [comment]
That was exactly what I was missing thank you!
