### ISSUE TITLE
Target and prediction are not excluded from the data drift report

### ISSUE THREAD

**Issue by yumoL** [evidentlyai/evidently#283]
According to the [evidently documentation](https://docs.evidentlyai.com/features/dashboards/column_mapping#column-mapping), if target and prediction are specified, they should be excluded from the data drift report. This is fine with evidently v0.1.49.dev0. However, when I upgraded evidently to v0.1.53.dev0, target and prediction are shown in the data drift report. 

I created a notebook to reproduce this bug: https://github.com/yumoL/evidently_bug_reproduction

**Comment by emeli-dral** [comment]
Hi @yumoL ,
you are right. 
We have change the behaviour of DataDriftTab()in the 0.1.51 release: https://github.com/evidentlyai/evidently/releases/tag/v0.1.51.dev0

The idea behind that was that some users wanted to obtain drift score for target and predictions together with all the rest features, but did not want to add an additional tab to the report like ```tabs=[DataDriftTab(), NumTargetDriftTab()]``` 

What are you thoughts on the topic? Do you think that target and prediction should not be there?

Sorry for the mess with the docs, we will update it shortly.

**Comment by yumoL** [comment]
Hi @emeli-dral , thanks for your quick reply. Should have read the release notes more carefully... I don't have a strong opinion on whether the target and prediction should be included in the data drift report or not, so it's fine to me that the target and prediction are included in the latest version :)

**Comment by emeli-dral** [comment]
@yumoL thank you!
Fixed in the docs.
