### ISSUE TITLE
[Feature Request] Verbosity level in Reports + API Docs!

### ISSUE THREAD

**Issue by jlopezpena** [evidentlyai/evidently#325]
Hi there!

I have been playing around with the new `Report` objects (I know they haven't been "officially" released yet, but wanted to get a taste!). Most of the stuff I was doing before with the `Dashboard` objects works just fine, but I couldn't find a way of changing the verbosity level of the metrics/widgets as I could before. Hopefully this is in your roadmap for the Report class, but I thought I'd mention it just in case :)

Which brings me to my second request. Trying to figure out how to do some stuff I frequently have to resort to going to the source code files. Your documentation does a great job at showing examples, but it is not easy to discover what all the available options or parameters for functions and classes are. It would be very helpful if the docs contained an "API Reference Guide" where one could explore each class/method/function and see its docstring, parameters, and default values!

**Comment by elenasamuylova** [comment]
Hi @jlopezpena! It's been already some time, just wanted to flag that we released:
- Metrics as individual components. You can now create a report by combining individual metrics and control "verbosity" this way https://docs.evidentlyai.com/tutorial#5.-customize-the-report
- API docs draft https://docs.evidentlyai.com/reference/api-reference

**Comment by elenasamuylova** [comment]
Thanks, @jlopezpena! Please let us know if face any other issues!
