### ISSUE TITLE
Cramér-von Mises (CVM) stattest for Drift Analysis

### ISSUE THREAD

**Issue by emeli-dral** [evidentlyai/evidently#343]
Cramér-von Mises Criterion: https://en.wikipedia.org/wiki/Cram%C3%A9r%E2%80%93von_Mises_criterion
How to contribute stattest for Drift Analysis: https://github.com/evidentlyai/evidently/wiki/Hacktoberfest

- [x] test implementation 
- [x] unittest
- [x] docs update 
- [x] example update

**Comment by emeli-dral** [comment]
Oh, I think I need to mention that there is already a PR on this specific test by @SangamSwadik waiting for minor fixes. 
But you can also choose a different test to implement, including a custom one if you use something different in your practice!

**Comment by ReubenThomasJohn** [comment]
Ah okay! Will see if there are any other stattests that need to be implemented. Thank you! @emeli-dral

**Comment by emeli-dral** [comment]
We recently added an [example](https://github.com/evidentlyai/evidently/blob/main/examples/how_to_questions/how_to_specify_stattest_for_a_testsuite.ipynb) of setting stattests in TestSuites. We are happy to receive PRs to update it with new drift detection methods!

**Comment by sankalp250** [comment]
I’d like to work on implementing the Cramér‑von Mises drift test. Could I be assigned?
