### ISSUE TITLE
Anderson–Darling stat test for Drift Analysis

### ISSUE THREAD

**Issue by emeli-dral** [evidentlyai/evidently#344]
Anderson–Darling test: https://en.wikipedia.org/wiki/Anderson%E2%80%93Darling_test 
How to contribute stattest for Drift Analysis: https://github.com/evidentlyai/evidently/wiki/Hacktoberfest

- [x] test implementation 
- [x] unittest
- [x] docs update 
- [x] example update

**Comment by AntonisCSt** [comment]
Hi, Is it possible to be assigned for this enhancement? I am new to contributing to open source (I also joined hackoctoberfest)

**Comment by emeli-dral** [comment]
We recently added an [example](https://github.com/evidentlyai/evidently/blob/main/examples/how_to_questions/how_to_specify_stattest_for_a_testsuite.ipynb) of setting stattests in TestSuites. We are happy to receive PRs to update it with new drift detection methods!
