### ISSUE TITLE
Fisher’s Exact test for Drift Analysis

### ISSUE THREAD

**Issue by emeli-dral** [evidentlyai/evidently#345]
Fisher’s Exact test: https://en.wikipedia.org/wiki/Fisher%27s_exact_test 
How to contribute stat test for Drift Analysis: https://github.com/evidentlyai/evidently/wiki/Hacktoberfest

- [ ] test implementation 
- [ ] unittest
- [ ] docs update 
- [ ] example update

**Comment by mertbozkir** [comment]
I would like to assign this issue to myself. I want to contribute evidently! 🤗

**Comment by emeli-dral** [comment]
Hi @mertbozkir! Thanks for your interest! 
Feel free to start working on the issue, we will review pull requests as they come!

**Comment by emeli-dral** [comment]
We recently added an [example](https://github.com/evidentlyai/evidently/blob/main/examples/how_to_questions/how_to_specify_stattest_for_a_testsuite.ipynb) of setting stattests in TestSuites. We are happy to receive PRs to update it with new drift detection methods!

**Comment by mertbozkir** [comment]
@SangamSwadiK asked below question in the Discord server 

> Hi, for the  fisher's exact test in the issues, would fisher for 2x2 contingency table suffice or should it be able to work for m x n contingency table ?
