### ISSUE TITLE
Hellinger distance for Drift Analysis

### ISSUE THREAD

**Issue by emeli-dral** [evidentlyai/evidently#347]
Hellinger distance: https://en.wikipedia.org/wiki/Hellinger_distance
How to contribute stattest for Drift Analysis: https://github.com/evidentlyai/evidently/wiki/Hacktoberfest

- [x] test implementation 
- [x] unittest
- [x] docs update 
- [x] example update

**Comment by Mathanraj-Sharma** [comment]
Hi, @emeli-dral I would like to take this, 

But I am new to evidently, could you please assign this to me and help me during the progress?

Are there any time constraints you have, do I need to complete it within a short time from assigning it to me?

**Comment by inderpreetsingh01** [comment]
Hi @Mathanraj-Sharma I already started working on this issue yesterday, forgot to mention it here, @emeli-dral please review this pr, will add tests and example shortly.

**Comment by emeli-dral** [comment]
Hi @Mathanraj-Sharma!

Thanks for your interest to contribute! We do not have a specific timeline here and will not formally "reserve" issues - though we encourage everyone to post when they start working on the issue so that others can see it (and maybe pick a different test). We will review contributions as they come, on the first come - first reviewed basis.

Note that you can also choose and implement a different statistical test of your choice!

**Comment by emeli-dral** [comment]
We recently added an [example](https://github.com/evidentlyai/evidently/blob/main/examples/how_to_questions/how_to_specify_stattest_for_a_testsuite.ipynb) of setting stattests in TestSuites. We are happy to receive PRs to update it with new drift detection methods!
