### ISSUE TITLE
Parallel backend support

### ISSUE THREAD

**Issue by niklasvm** [evidentlyai/evidently#35]
Hi there

Thank you for a great package. I would like to request whether a parallel backend could be supported when running drift calculations across large numbers of features.

Regards

**Comment by emeli-dral** [comment]
Hi @niklasvm , and thanks for opening up the issue!

It is in the roadmap. Unfortunately, not immediate one due some resource constraints, but we will definitely add this.

**Comment by niklasvm** [comment]
Amazing, thank you!

**Comment by emeli-dral** [comment]
Instead of the parallel backend we will support Spark. This should speed up calculations
