### ISSUE TITLE
Add a new data drift detection method to Evidently

### ISSUE THREAD

**Issue by emeli-dral** [evidentlyai/evidently#378]
This is an open issue. We invite you add new data drift detection tests or metrics to the Evidently library. 

Here are general instruction on how to add a new test:
https://github.com/evidentlyai/evidently/wiki/Hacktoberfest 

We invite you contribute new drift detection methods that you consider useful. If you want to add a new method, you can create a separate issue to let us know that you are working on it. You can also directly send the pull-request. 

Please do share some details about the new method and when it can be useful (or when you are using it!) 

Each contribution should contain:
- Test implementation
- Unittest
- Docs update
- Example update

**Comment by emeli-dral** [comment]
Our goal is not to implement as many statistical tests as possible (as the choice can be confusing to the users!) but to add tests that have different properties and might be chosen over already existing ones for a specific reason. 

We highly welcome additions that come from your practice: e.g., if you, as a data scientist, already use a different drift detection method in your work. 

Here are some ideas for methods you can explore:
- Bhattacharyya distance https://en.wikipedia.org/wiki/Bhattacharyya_distance 
- Energy distance ​https://en.wikipedia.org/wiki/Energy_distance ​ 
- Total variation https://en.wikipedia.org/wiki/Total_variation 
- Matrix or vector norm https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html 
 
You can also study implementations that exist in research papers and propose ones that could be a valuable addition. Please cite the paper if you implement any of the approaches proposed by the authors so that we reflect it in the documentation.

**Comment by aswinvk28** [comment]
Mahalanobis distance is also another candidate. 

Here is a paper that discusses about Mahalanobis distance and its applications in Outlier detection
[https://core.ac.uk/download/pdf/233075917.pdf](https://core.ac.uk/download/pdf/233075917.pdf)
