### ISSUE TITLE
The dashboard showing Loading... on local Jupyter Notebook

### ISSUE THREAD

**Issue by aswinvk28** [evidentlyai/evidently#384]
**Steps taken**
I installed nbextension using
`jupyter nbextension install --sys-prefix --symlink --overwrite --py evidently`

Enabled nbextension evidently
`jupyter nbextension enable evidently --py --sys-prefix`

**Preview of Error**
![image](https://user-images.githubusercontent.com/1046939/195439597-642d5946-6ec9-4de2-8c7f-47a85be6c6b2.png)

**Issue**
Still I get the above error, Loading...

**Comment by emeli-dral** [comment]
Hi @aswinvk28 ,

what OS do you use?

Could you please try to specify ```mode``` parameter in ```show``` method, and call it like this:
```bcancer_target_drift.show(mode='inline')``` ?

**Comment by LangDaoAI** [comment]
mode='inline' works!  @emeli-dral

**Comment by aswinvk28** [comment]
> Hi @aswinvk28 ,
> 
> what OS do you use?
> 
> Could you please try to specify `mode` parameter in `show` method, and call it like this: `bcancer_target_drift.show(mode='inline')` ?

Yes, thank you @emeli-dral mode='inline' works
