### ISSUE TITLE
Predicted Vs Actual is not setup to work ?

### ISSUE THREAD

**Issue by Joshwlks** [evidentlyai/evidently#393]
Hi there,

I am trying to set up a regression performance dashboard that includes the predicted vs actual metric, just like what is shown in the docs [here](https://docs.evidentlyai.com/reports/reg-performance#2.-predicted-vs-actual). However, looking through the codebase it seems the predicted vs actual metric is not fully implemented? There is only a metric file for it and not a calculation, monitor or analyzer? 

For context, I have integrated evidentlyai with Prometheus and Grafana, so have [this ](https://github.com/evidentlyai/evidently/blob/main/examples/integrations/grafana_monitoring_service/dashboards/regression_performance.json)dashboard json file pointing at the regression performance analyzer.

**Comment by elenasamuylova** [comment]
Hi @Joshwlks, you caught us in the middle of refactoring as we move to the new API (where you can get a Report comprised of individual Metrics). All the metrics will be implemented there very soon. 

You can still get the regression performance dashboard, including this plot, as shown in the docs, using the old Dashboards API and calling the `RegressionPerformanceTab` https://docs.evidentlyai.com/features/dashboards/generate_dashboards

**Comment by Joshwlks** [comment]
Thanks for the reply! Which version of the repo do you recommend using to achieve what I am looking for?

**Comment by elenasamuylova** [comment]
Hi @Joshwlks!

Apologies, as I missed you specifically referring to the Grafana example. 

I am afraid there is no easy way to pass this plot to the Grafana in the existing example. The thing is that Predicted VS Actual is not technically a "metric" (there is nothing additional that Evidently computes). Both "target" and "prediction" are passed to Evidently as inputs in the first place. 

Evidently generates the Predicted VS Actual visualization in the Evidently HTML reports output, but it does not produce any specific JSON output that can be useful in real time. 

If you use Grafana for visualization, you'd need to write some custom code to implement and pass this data (predictions and target) directly to Prometheus from your service, bypassing the Evidently service.
