### ISSUE TITLE
Contribution Guidelines 

### ISSUE THREAD

**Issue by DRMALEK** [evidentlyai/evidently#41]
Hi there,

I think it is really a good package, and I want to ask about how contributions can be made to this project?

Thanks.

**Comment by emeli-dral** [comment]
Hi @DRMALEK! 

Awesome that you like the package! We plan to add contribution guidelines in the fall. 

Right now, it is a more manual process and review. If you want to contribute, let me know what you think to add - we can give you some pointers. 

We can also chat in our Discord: https://discord.com/invite/xZjKRaNp8b

**Comment by emeli-dral** [comment]
Hi,
here is a contributing guide: https://github.com/evidentlyai/evidently/blob/main/CONTRIBUTING.md 

We are happy to get contributions to any part of the library, from documentation to the core modules and new dashboards :)
