### ISSUE TITLE
DataDriftProfileSection for categorical features is not working with scipy version >= 1.7.1

### ISSUE THREAD

**Issue by nadcharin** [evidentlyai/evidently#42]
I've encountered an issue when trying to generate DataDriftProfileSection of categorical features column with Scipy version >= 1.7.1 after downgrade Scipy to 1.6.3 everything is working fine.

**Comment by emeli-dral** [comment]
Hi @nadcharin 
Thanks for reporting! That will be fixed in the near term.

**Comment by emeli-dral** [comment]
Hi there,

it is fixed, one more thanks for the reporting.
