### ISSUE TITLE
library issue : DataDrift,DataQuality

### ISSUE THREAD

**Issue by IITGoaPyVidya** [evidentlyai/evidently#432]
Hello community,

when I try to import libraries
1. from evidently.metric_preset import DataDrift, NumTargetDrift
2. from evidently.test_preset import DataQuality, DataStability

I am getting following error 
1. cannot import name 'DataDrift' from 'evidently.metric_preset'
2. cannot import name 'DataQuality' from 'evidently.test_preset'

this was just example notebook from evidently.

Any suggestions are highly appreciated.

thanks,

**Comment by elenasamuylova** [comment]
Hi @IITGoaPyVidya! There was an update to the names of the presets last week, as we now have both Metric presets and Test presets. https://github.com/evidentlyai/evidently/releases/tag/v0.1.59.dev0 

Here is the Getting Started tutorial (with updated API): https://github.com/evidentlyai/evidently/blob/main/examples/sample_notebooks/getting_started_tutorial.ipynb

Here are all test presets:
https://github.com/evidentlyai/evidently/blob/main/examples/sample_notebooks/evidently_test_presets.ipynb

Here are all metric presets
https://github.com/evidentlyai/evidently/blob/main/examples/sample_notebooks/evidently_metric_presets.ipynb

In your case, you need to import for Metric Presets:
from evidently.metric_preset import DataDriftPreset
from evidently.metric_preset import TargetDriftPreset

For Test Presets:
from evidently.test_preset import DataStabilityTestPreset
from evidently.test_preset import DataQualityTestPreset

**Comment by elenasamuylova** [comment]
We should have updated all the examples in the documentation but could have overlooked something. Could you point to the example notebook you refer to? We'll update it as well!

**Comment by IITGoaPyVidya** [comment]
@elenasamuylova Thanks for timely response! 

I renamed those import statements now its working fine. I was referring [getting started tutorial](https://colab.research.google.com/drive/1j0Wh4LM0mgMuDY7LQciLaUV4G1khB-zb). that colab notebook is yet to be updated as per new changes.

However this is all for structured data, I want to analyse drift for unstructured data, is there any guidebook on this?

**Comment by elenasamuylova** [comment]
Hi @IITGoaPyVidya, thanks - we will update that one soon. 

Unfortunately, right now, Evidently only natively supports tabular data inputs. As a workaround, some users feed embeddings in the tools, but it is usually hard to interpret.

**Comment by elenasamuylova** [comment]
Do you have text or image data?

**Comment by IITGoaPyVidya** [comment]
I have text data, I will be working around NLP

**Comment by elenasamuylova** [comment]
Thanks for clarifying! We plan to add support for the text data next, but right now, there is no dedicated implementation yet.

**Comment by elenasamuylova** [comment]
@IITGoaPyVidya, you can also have a look at this example notebook https://github.com/evidentlyai/evidently/pull/427 (work in progress, I believe) by @SangamSwadiK where he demonstrates exactly the idea of how you can feed text data in Evidently right now.
