### ISSUE TITLE
Some of the Test are not working

### ISSUE THREAD

**Issue by samuelamico** [evidentlyai/evidently#486]
<img width="689" alt="Screen Shot 2022-12-26 at 11 08 57" src="https://user-images.githubusercontent.com/47945745/209557543-77367867-e6b2-4071-86fb-90a6063749be.png">

Some of the Tests are not working. The names are not correct ? or they are not present in the module anymore ?
If the have been changed (renamed) can you provide a list of the tests with the old and new name ? Thanks.

**Comment by elenasamuylova** [comment]
Hi @samuelamico, could you check which Evidenly version you are using?

`TestNumberOfNulls` (and similar null-related tests) were renamed to `TestNumberOfMissingValues` in one of the earlier releases.

You can see the **log of changes** in the release notes, but it might be that something was missed: 
https://github.com/evidentlyai/evidently/releases

Sorry for the confusion, if any!

The current Evidently version (0.2.0 onwards) is considered stable; there should be no more changes to the names of existing tests. To **see the current names** of all tests, you can check the "All tests" example notebooks (Jupyter: https://github.com/evidentlyai/evidently/blob/main/examples/sample_notebooks/evidently_tests.ipynb), consult the API reference or "All tests" table: https://docs.evidentlyai.com/reference/all-tests

**Comment by samuelamico** [comment]
Thanks for the update.
