### ISSUE TITLE
`save_html` fails without nbextension

### ISSUE THREAD

**Issue by marcellovictorino** [evidentlyai/evidently#496]
Hi!
According to the documentation:
![image](https://user-images.githubusercontent.com/18636680/214329567-f0f117b1-a81f-4069-ad9c-bdb687cb75d0.png)

> If you only want to generate interactive reports as HTML files or JSON profiles, the installation is now complete.

But in order for me to use the `save_html` method, I had to carry on installing and activating the `nbextension` (with symlink).

I was getting the following error (which pointed me towards installing the `nbextension` in the first place):

> File "/usr/local/Caskroom/mambaforge/base/envs/metaflow_.../lib/python3.8/site-packages/evidently/utils/dashboard.py", line 134, in file_html_template:
>     lib_block = f"""<script>{__load_js()}</script>""" if params.embed_lib else ""
> 
> File "/usr/local/Caskroom/mambaforge/base/envs/metaflow_.../lib/python3.8/site-packages/evidently/utils/dashboard.py", line 191, in __load_js:
>     return open(os.path.join(STATIC_PATH, "index.js"), encoding="utf-8").read()
> FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/Caskroom/mambaforge/base/envs/metaflow_.../lib/python3.8/site-packages/evidently/nbextension/static/index.js'

The question is:
* Is it really required to install `nbextension` just to generate/save the interactive HTML report?
* If so, would be worth updating the documentation

**Comment by emeli-dral** [comment]
Hey @Liraim ,
could you please take a look?

I'm using python=3.8, evidently=0.2.2 and I was able to generate html file without ```nbextension``` installed. (but on mac os).

**Comment by Liraim** [comment]
Hi,

Do you use conda for installing package?

If so, there some issues with native conda package of evidently (it doesn't have embedded resources for html resources).
For now you should use package from Pypi.

**Comment by marcellovictorino** [comment]
Ah! That must be it!
I use it within Metaflow flows. Which natively supports conda based installations (although possible to use pip and upcoming support for poetry)

Thanks! I will give it a try

As a note: might be worth adding to the documentation such caveat 👍

Feel free to close this issue.

**Comment by emeli-dral** [comment]
Hi @marcellovictorino ,

How is it going? Could you let me know if you managed to install the package using pip?

I also wanted to share that we decided to fully support conda installation and hopefully, it will be working in a matter of days.

**Comment by emeli-dral** [comment]
Thank you @marcellovictorino!

We updated evidently package building script, and since 0.2.4 it supports conda installation. 
If anything seems broken, feel free to open an issue!
