### ISSUE TITLE
evidently.model_profile.Profile.calculate not populating default float values for 'confidence' or 'drift_share'

### ISSUE THREAD

**Issue by Jay-Down** [evidentlyai/evidently#51]
Hi, when running through the [mlflow integration tutorial](https://github.com/evidentlyai/evidently/blob/main/evidently/tutorials/mlflow_integration.ipynb), the `Profile.calculate` function fails with TypeError exceptions, stating that mathematical operations are not supported between floats and NoneTypes.

The point where this is  failing is in the `dataset_drift_evaluation` function when comparing the calculated drift statistics with the default thresholds, as shown in the attached traceback screenshot:
![conf_level_unsupported_operands](https://user-images.githubusercontent.com/33293631/132728064-313f575d-1b78-4a73-800b-8128c21fbd38.PNG)

If I explicitly specify: 
`column_mapping['drift_conf_level'] = 0.95`
`column_mapping['drift_features_share'] = 0.5`

then everything works as expected.

(evidently version ==  0.1.23.dev0)

**Comment by elenasamuylova** [comment]
Hi @Jay-Down! We just recently implemented the Dataset Drift calculation using column mapping https://docs.evidentlyai.com/reports/data-drift#1-data-drift-summary. So there is no need to write a custom function anymore! We will update this example shortly. Stay tuned!

**Comment by emeli-dral** [comment]
Hi @Jay-Down ,

Thank you a lot for reporting this! 
Just made a fix, should be working now without explicit specification of the ```drift_conf_level``` and  ```drift_features_share``` in the ```column_mapping``` or config (for CLI running).
