### ISSUE TITLE
Multiclass classification bug

### ISSUE THREAD

**Issue by mshislam** [evidentlyai/evidently#516]
https://github.com/evidentlyai/evidently/blob/87c38cedaaa8efe4ecd4bfb237ee51bd73725747/src/evidently/metrics/classification_performance/base_classification_metric.py#L54

In the previous line reference if we want to do a multiclass classification you only get classes from prediction features, some classes can happen to not be predicted in a timeframe and if this class is in the target, it will not be added to the confusion matrix get the issue 
because labels in the target are not identified as ac classes because they are not present in the prediction. 

how could I add classes that were not predicted but in target as part of the unique labels for the multiclassification?

ValueError: At least one label specified must be in y_true

**Comment by emeli-dral** [comment]
Hi @mshislam ,
Thank you for letting us know!

We released the fix in the latest package (v 0.2.6); Fill free to update your local evidently version and let us know if something else needs to be improved :)

**Comment by mshislam** [comment]
Hello Emeli,

Thanks a lot for reaching out and looking forward to using the new version.

Regards,
Mohamed Islam

On 6 Mar 2023, at 12:01 PM, emeli-dral ***@***.***> wrote:

﻿

Hi @mshislam<https://github.com/mshislam> ,
Thank you for letting us know!

We released the fix in the latest package (v 0.2.6); Fill free to update your local evidently version and let us know if something else needs to be improved :)
