### ISSUE TITLE
Column mapping not working

### ISSUE THREAD

**Issue by raajeshlr** [evidentlyai/evidently#52]
Column mapping is not working in the system, I get "TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'" or Zero Division Error when I try to use.
OS : Windows
Python 3.7
Even I tried in Google Colab, still its not working

**Comment by emeli-dral** [comment]
Hey @raajeshlr ,

Thanks for letting us know! It definitely should not be like this, let's figure out what has happened. 
Could you please share a screenshot with the full error output?

And there are a couple of questions, which also will help to solve the case faster:
- what report you are building?
- how the ```column_mapping``` dict looks like (if you prefer not to share feature names - that’s completely OK)?
- what is the evidently package version (```print(evidently.__version__)```) ?

**Comment by raajeshlr** [comment]
Hi @emeli-dral 
Thanks for the response, let me share the details.
- I am using Boston dataset only and trying to generate Data Drift and Num Target Drift.
- Evidently package version is 0.1.23.dev0
- Error is **unsupported operand type(s) for -: 'float' and 'NoneType'** when I use column mapping, attached the screenshot.
- My Column mapping is
                                        column_mapping = {}
                                        column_mapping['target'] = 'target'
                                        column_mapping['prediction'] = None
                                        column_mapping['datetime'] = None
                                        column_mapping['numerical_features'] = ['CRIM','ZN','INDUS','NOX','RM','AGE','DIS','TAX',
                                       'PTRATIO','B','LSTAT']
                                       column_mapping['categorical_features'] = ['CHAS','RAD']

- Please connect with me at https://www.linkedin.com/in/raajeshlr/
- I am eager to discuss about this. 
<img width="417" alt="error screenshot" src="https://user-images.githubusercontent.com/37265950/133568077-7a615c51-7318-4a94-861b-687f318c92f0.png">

**Comment by emeli-dral** [comment]
Hi @raajeshlr ,

Got it, this is the problem we recently fixed in the latest version. 

Could you please try to update the package and run the example again?
```pip install evidently --upgrade``

And than run two following commands in the terminal from the evidently directory:
```jupyter nbextension install --sys-prefix --symlink --overwrite --py evidently```
```jupyter nbextension enable evidently --py --sys-prefix```
