### ISSUE TITLE
consider compability with pyYAML >=6.0

### ISSUE THREAD

**Issue by davidbange** [evidentlyai/evidently#526]
Dear Evidently Crew,

could you consider compability with pyYAML >=6.0 ?
Because currently we had to upgrade our googleads version to 37.0.0 wich led to a pip dependency conflict making us unable to use evidently any longer :(

#9 344.6 The conflict is caused by:
#9 344.6     googleads 37.0.0 depends on PyYAML<7.0 and >=6.0
#9 344.6     evidently 0.2.6 depends on PyYAML~=5.1

Best Regards
David

**Comment by emeli-dral** [comment]
Hi @davidbange!

Thank you for bringing this up. Initially, we fixed  PyYAML~=5.1 for compatibility with google colab.
We believe that the issue is already solved. We'll double-check it and update the dependency in the next release.

**Comment by rickyschools** [comment]
Hi team - 

I was wondering when the 0.2.7 release, which I believe would include this patch, was scheduled for? My team is getting burned by this PyYAML dependency too (which stems from the `databricks-feature-store` package requiring PyYAML<7.0 and >=6.0. Thanks in advance and appreciate all the work the group has put into this great package.

Cheers,

RS

**Comment by elenasamuylova** [comment]
Hi @rickyschools, @davidbange, 

This fix has been released today: https://github.com/evidentlyai/evidently/releases/tag/v0.2.7
