### ISSUE TITLE
data missing in the report

### ISSUE THREAD

**Issue by superyang713** [evidentlyai/evidently#56]
Hi 

I was trying to generate a classification dashboard. The "reference" dataframe has 128770 rows, however, the dashboard only shows that it has 122 rows (number of objects). And for "current" dataframe, it has 632337 rows, but the dashboard only shows it has 1079 rows. I am not sure what went wrong. 

Yang

**Comment by emeli-dral** [comment]
Hi @superyang713 

Looks very interesting. My current guess is that it can be related to the ```nan``` values.
Could you please check the amount of the rows which have a least one ```nan``` value in? I assume that the amount of skipped rows will be equal to the amount of the rows with nans, but lets check first.

The following commands can be handy:
```
#column-based nans statistics
data.isna().sum(axis=0)

#row-based nans statistics
data.isna().sum(axis=1)

#total amount of the rows with nans
raw_data.isna().sum(axis=1).sum()
```

**Comment by superyang713** [comment]
Thank you for the reply. You are right, the dataset has missing values.  Sorry I just started using the package, and did not know that I have to fill out the missing values before generating the dashboard.

My trained model is actually a sklearn pipeline that has an imputer  and other transformers in it.  So I only need to feed the raw data into the model. But for generating the Dashboard, I have to use fill out the missing values first then. Thank you for the response.

**Comment by emeli-dral** [comment]
Hi @superyang713 ,

No worries it all! I wanted to thank you for bringing this up! To be honest, it is not exactly how we plan to handle missing values (currently all the rows with the missing values are just ignored). We are going to offer some more ```nan``` handling strategies there.

**Comment by ahsan876** [comment]
> copy

Okay thanks @emeli-dral  I will check with new release and validate it. Thanks for the response.

**Comment by zawster** [comment]
Okay thanks @emeli-dral I will check with new release and validate it. Thanks for the response.
