### ISSUE TITLE
Production data without label column

### ISSUE THREAD

**Issue by prarshah** [evidentlyai/evidently#57]
In case of target feature is missing in production data, gives "'TargetNameWidget' object has no attribute 'wi'"
Which metrics are supported incase the labels are missing for production data

**Comment by emeli-dral** [comment]
Hi @prarshah ,
In case label data are unavailable there are two reports you still can build:
1. [Data Drift](https://docs.evidentlyai.com/reports/data-drift)
2. If you have model predictions, then you also can build [Numerical Target Drift](https://docs.evidentlyai.com/reports/num-target-drift) or [Categorical Target Drift](https://docs.evidentlyai.com/reports/categorical-target-drift) report (depending on the problem statement you working on). For these reports please set the ```predictions``` column  in the ```column_mapping```.

All other reports are related to the model performance and expect to get labels for quality estimation. But for early assessment both Data Drift  and Prediction Drift can be handy
