### ISSUE TITLE
Error while using Drift on embeddings

### ISSUE THREAD

**Issue by SangamSwadiK** [evidentlyai/evidently#571]
Hi, I'm redoing the notebook on encoders with Drift which was previously univariate detection.
I'm facing the below error when running the embedding drift methods.

![image](https://user-images.githubusercontent.com/35230623/233413981-1a3c307b-0a0f-42bd-8a11-b71d40e2bc50.png)

cc @elenasamuylova

**Comment by emeli-dral** [comment]
Hey @SangamSwadiK ,
Thank you for letting us know!

Could you please share with us a link to your colab so that we could see the whole error trace together with the code?

**Comment by 0lgaF** [comment]
Hi @SangamSwadiK !
Thanks for letting us know about this issue! We have fixed the error and the changes will be available in the next release.

By the way, we noticed that you're using the "p_value" parameter in the drift detection methods in your notebook. Just a heads up, we've renamed it to "quantile_probability" in the new release, so you'll need to make that change in your notebook. 
p_value=0.05 -> quantile_probability=0.95

If you have any inquiries, please do not hesitate to ask us!

**Comment by 0lgaF** [comment]
fixed in https://github.com/evidentlyai/evidently/pull/586
