### ISSUE TITLE
Grafana example is broken

### ISSUE THREAD

**Issue by boada** [evidentlyai/evidently#573]
none of these methods exist: 

> from evidently.model_monitoring import CatTargetDriftMonitor
> from evidently.model_monitoring import ClassificationPerformanceMonitor
> from evidently.model_monitoring import DataDriftMonitor
> from evidently.model_monitoring import DataQualityMonitor
> from evidently.model_monitoring import ModelMonitoring
> from evidently.model_monitoring import NumTargetDriftMonitor
> from evidently.model_monitoring import ProbClassificationPerformanceMonitor
> from evidently.model_monitoring import RegressionPerformanceMonitor

the readme points to several code areas which don't exist. eg. https://github.com/evidentlyai/evidently/blob/main/src/evidently/model_monitoring/monitors/

a search of the api docs and the repo in general didn't surface replacements for these functions.

**Comment by boada** [comment]
seems to work with `evidently==0.2.8` and can be fixed by pinning the version in the [dockerfile](https://github.com/evidentlyai/evidently/blob/main/examples/integrations/grafana_monitoring_service/Dockerfile#L11)

**Comment by wanderson42** [comment]
None of these methods still exist in the most current version (==0.6.5).  Any reason for this?

```
from evidently.model_monitoring import CatTargetDriftMonitor
from evidently.model_monitoring import ClassificationPerformanceMonitor
from evidently.model_monitoring import DataDriftMonitor
from evidently.model_monitoring import DataQualityMonitor
from evidently.model_monitoring import ModelMonitoring
from evidently.model_monitoring import NumTargetDriftMonitor
from evidently.model_monitoring import ProbClassificationPerformanceMonitor
from evidently.model_monitoring import RegressionPerformanceMonitor
```
