### ISSUE TITLE
How to change the Standard Deviation which is by default 1

### ISSUE THREAD

**Issue by nageshsinghc4** [evidentlyai/evidently#59]
How to change the Standard Deviation to like 2 or 3, which is by default 1 in the DataDrift Dashboard?

**Comment by emeli-dral** [comment]
Hi @nageshsinghc4 

Unfortunately, we do not have this option in the configurations yet. 
At the moment in can be done in the source code by changing the implementation of the https://github.com/evidentlyai/evidently/blob/main/evidently/widgets/data_drift_table_widget.py

To be more precise, this:
```reference_std = np.std(reference_data[feature_name][np.isfinite(reference_data[feature_name])], ddof=1)```
should be updated somewhat like that:
```
n_std = 3
reference_std = n_std*np.std(reference_data[feature_name][np.isfinite(reference_data[feature_name])], ddof=1)
```
And after this update the project should be rebuilt internally.

Do you think this parameter should be presented in the config as well?

**Comment by nageshsinghc4** [comment]
Hi @emeli-dral,

Thanks that is quite helpful. 
Indeed I think this should be included because in some use cases we need to consider normal distribution and filter out data points that lie within 3 Standard Deviation along with the mean.
