### ISSUE TITLE
Calculate Function throws unpacking error

### ISSUE THREAD

**Issue by nilamshete3001** [evidentlyai/evidently#61]
Hi Team,
I ran the example notebook provided on git on my local machine but getting the following error when I call the "calculate" function on the Dashboard or Profile object. 
![image](https://user-images.githubusercontent.com/8390850/136078117-75174570-12b8-406d-8050-2422d2bdcc5c.png)

Can someone help me to understand why this is happening?
Thanks!

**Comment by emeli-dral** [comment]
Hi @nilamshete3001 , 
thanks for reporting, that's an issue on our side.
Working on a bug fix!

**Comment by nilamshete3001** [comment]
Hi @emeli-dral,
Yes, it's working on my end as well 👍 
Thank you for your prompt response and resolution. 
Looking forward to exploring the library and include in our model monitoring framework.
Thanks again!
