### ISSUE TITLE
what does 1m, 0.5m or 1B, 2B means in axes ticks labels of data/target drift dashboard

### ISSUE THREAD

**Issue by Rajendra-mckesson** [evidentlyai/evidently#635]
see of eg. image below.

<img width="988" alt="target" src="https://github.com/evidentlyai/evidently/assets/124593281/c1901322-90ef-41c0-9ae3-0fbed5af164b">

**Comment by 0lgaF** [comment]
Hi @Rajendra-mckesson , 

The x-axis splits all values of a numerical feature into bins. The y-axis (height of the bar) represents the number of objects in the dataset that fall into that range.

The values you refer to on the x-axis show the corresponding bin value. (If you hover over the left age of any histogram bin, it will show the left edge of a given bin). 

When the number is large, the number is shortened. "K" stays for a thousand, "M" stays for million, "B" for billion.  

On you image, it appears you are dealing with a numerical feature that contains large numbers (it takes values from 0 to 5 Billion). So the annotation is shortened to 1B (1 billion),  2B and so on.
