### ISSUE TITLE
Trace 0 on charts of RegressionPerformanceTab

### ISSUE THREAD

**Issue by Pakard1** [evidentlyai/evidently#67]
Hi, 

I am having problems trying to understand if trace 0 on graphs has any meaning or if it just a trace on y = 0.

Is it possible to remove this trace? My graph outputs doesnt scale well with it.

Thank you!

**Comment by Pakard1** [comment]
![image](https://user-images.githubusercontent.com/57632070/138063863-24bc5e01-5f4a-4320-9660-03e3bb4d28f9.png)

I am referencing this part of code in reg_pred_and_actual_in_time_widget.py

If you change showlegend to True you cant filter out, the other 2 traces, Actual/Current and Predicted legend are show by default

**Comment by emeli-dral** [comment]
Won't be fixed, we decided to keep the zero trace in the default configurations.
However, the tool allows to create a custom widgets: https://github.com/evidentlyai/evidently/tree/main/examples/how_to_questions/custom_widget_and_tab_example 
The zero line can be entirely removed there.
