### ISSUE TITLE
No module named 'evidently.dashboard'

### ISSUE THREAD

**Issue by jilan804** [evidentlyai/evidently#671]
why not installed on my notebook instance

**Comment by elenasamuylova** [comment]
Hi @jilan804, 

Most likely you are using old Evidently API with a newer Evidently version that no longer has a `dashboard` object.

You can fix the Evidently version to 0.2.8 or earlier, or migrate to the new `Report `object (recommended).

This should help: https://docs.evidentlyai.com/support/migration
