### ISSUE TITLE
Data Drift by Feature standard deviation from mean

### ISSUE THREAD

**Issue by Pakard1** [evidentlyai/evidently#68]
Hi,

I was using the Data Drift Tab by Feature.

Is it possible to change the green area that covers one standard deviation from the mean? I wanted it to be 2 std deviation making it less sensible to data drift

Thank you

**Comment by 0lgaF** [comment]
Hi @Pakard1 

We added this functionality in #122 
You can get more details here https://docs.evidentlyai.com/user-guide/customization/options-for-quality-metrics
