### ISSUE TITLE
Diffrent sizes of refrence dataset and current dataset

### ISSUE THREAD

**Issue by prarshah** [evidentlyai/evidently#69]
@emeli-dral
In case the reference dataset which is usually the historic dataset is much bigger in size as compared to the current dataset, in that case, should we rescale the frequencies so that we can compare distributions of similar size?

ref:
https://commons.apache.org/proper/commons-math/javadocs/api-3.3/org/apache/commons/math3/stat/inference/ChiSquareTest.html

**Comment by emeli-dral** [comment]
We have added several drift detection metrics (like Wassershtein distance), which are less sensitive to the dataset sizes.
