### ISSUE TITLE
Add density plot as an option to DataDriftPreset Report

### ISSUE THREAD

**Issue by elutins** [evidentlyai/evidently#705]
I am interested in using the `DataDriftPreset` to create a drift `Report`. It would be beneficial for the resulting report to show density plots opposed to the histogram count plots. The purpose being that often times I am trying to compare a `current` dataframe with a much smaller sample size, to a `reference` dataframe that was used in training and contains much more data compared the current dataframe. 

the full code I am using to generate the report looks like this 
```
from evidently.report import Report
from evidently.metric_preset import DataDriftPreset

data_drift_report = Report(
    metrics=[
        DataDriftPreset(
            num_stattest=z_stat_test,
            cat_stattest='psi',
            num_stattest_threshold=0.2,
            cat_stattest_threshold=0.2
        )],
)

data_drift_report.run(reference_data=df_reference, current_data=df_target, column_mapping=None)
data_drift_report.show(mode='inline')
```

**Comment by elenasamuylova** [comment]
Hi @elutins, 

Thanks for sharing the feature request!

We will add the option to switch from the absolute number of observations to the percentage scale on a histogram. (Both options will be available on the plot). This way, if you have a significant difference in sample size, you can switch to the % view to visually compare the distributions on a histogram. 

This will be included in an upcoming release in August.

Hopefully, this will solve the visibility issue!

**Comment by elutins** [comment]
Sounds great! looking forward to it

**Comment by elenasamuylova** [comment]
Hi @elutins, to update - the ability switch between absolute and % view on distrbution plots have been added in Evidently 0.4.1. Hope it will make the distribution analysis more convenient. 

 https://github.com/evidentlyai/evidently/releases/tag/v0.4.1

**Comment by elutins** [comment]
looked through the code and still wondering how can this parameter can be specified in a `Report`? eg I am using `ColumnSummaryMetric` to produce a `Report`

```
metrics = [ColumnSummaryMetric(column_name=col) for col in self.live_failed_features]
data_drift_report = Report(metrics=metrics)  # DataDriftPreset(num_stattest=z_stat_test)
data_drift_report.run(reference_data=df_ref, current_data=df_current)
``

**Comment by elutins** [comment]
@elenasamuylova thanks for clarifying! great feature addition 💯
