### ISSUE TITLE
Tests not running on all columns by default

### ISSUE THREAD

**Issue by elutins** [evidentlyai/evidently#708]
#### Test* not running on all columns by default as stated in the documentation

According to the documentation on this page (referring to `TestMeanInNSigmas()` and `TestColumnShareOfMissingValues()` in particular), the test is supposed to run on all numeric and all columns by default, without having to pass in a `column_name`. however I get an error when not passing in a `column_name` parameter. Is this the expected behavior? I'd like to run on all columns by default.

Full code below:
```
cmap = ColumnMapping(numerical_features=numeric_subset, categorical_features=cat_subset)
drift_suite = TestSuite(
    tests=[
        TestMeanInNSigmas(),
        TestColumnShareOfMissingValues()
    ],
)

drift_suite.run(reference_data=tmp_ref[numeric_subset+cat_subset], current_data=df_target[numeric_subset+cat_subset], column_mapping=cmap)
```

and corresponding error
```
TypeError: __init__() missing 1 required positional argument: 'column_name'
```

**Comment by elenasamuylova** [comment]
Hi @elutins, could you point to the specific page in the docs where it is stated? We'll correct it. 

Tests like `TestMeanInNSigmas()` are column-level tests so they **always require a column_name**. You can quickly generate column-level tests for all columns in the dataset using `generate_column_tests` function (docs here: https://docs.evidentlyai.com/user-guide/tests-and-reports/test-metric-generator#column-test-generator).

If you use presets like `NoTargetPerformanceTestPreset()` (which includes both `TestColumnShareOfMissingValues` and 
`TestMeanInNSigmas()`) - the generation of multiple per-column tests is already included inside the preset.

If you use these tests individually as a part of a custom Test Suite - you should use the generator if you want to apply the same column-level test to multiple columns.

**Comment by elenasamuylova** [comment]
To clarify, not all tests require this.

Some tests are **dataset-level**, e.g. `TestShareOfMissingValues()` - it will evaluate the overall share of missing values in the dataset, or `TestShareOfColumnsWithMissingValues()`. They do not require column names. 

Other tests like `TestColumnShareOfMissingValues()` are **column-level**, and work as described above.

To understand which test is column-level, and which is dataset-level, you can check the example notebook
https://docs.evidentlyai.com/reference/all-tests#data-integrity

**Comment by elenasamuylova** [comment]
To clarify, not all tests require this.

Some tests are **dataset-level**, e.g. `TestShareOfMissingValues() -` it will evaluate the overall share of missing values in the dataset, or `TestShareOfColumnsWithMissingValues()`. They do not require the column name parameter. 

Other tests like` TestColumnShareOfMissingValues() `are **column-level,** and work as described above.

To understand which test is column-level, and which is dataset-level, you can check the example notebook
https://github.com/evidentlyai/evidently/blob/main/examples/sample_notebooks/evidently_tests.ipynb (tests are grouped accordingly) or check the "All tests table" https://docs.evidentlyai.com/reference/all-tests#data-integrity (it is noted in the "Description" column related to the individual tests).

**Comment by elutins** [comment]
Thanks for clarifying @elenasamuylova! I found that `generate_column_tests` fits my use case the best so going to proceed with that.

[Here](https://docs.evidentlyai.com/reference/all-tests) is the documentation page which I was referring to, however think I was misreading it. Since `TestMeanInNSigmas` is under the `NoTargetPerformancePreset()` umbrella, it would automatically be applied to all numeric columns, is that right?

**Comment by elenasamuylova** [comment]
Thanks @elutins - indeed, on the top of the page, it explains the contents of the `NoTargetPerformancePreset()`. It will work as you mention. The `TestMeanInSigmas` will apply to all numeric columns or to all numeric columns in the list you pass (in case you pass a list of `columns` as a parameter directly to the preset).

The page indeed might be mildly confusing :) However, for now, we decided to keep the list of all individual tests and the description of the contents of the presets on the same page. Many users start with presets and then design custom test suites by "editing" the presets so it appears helpful to keep it on the same page.

Glad it is solved! Please do ask if you need any more help.
