### ISSUE TITLE
Bug: Similar Test & Metric with different parameter support

### ISSUE THREAD

**Issue by ketangangal** [evidentlyai/evidently#716]
Hello @emeli-dral , 

As can be seen from the image  **TestEmbeddingsDrift**  with different parameters does not support **TestSuite** and we end up having result of only first written Test. 

![image](https://github.com/evidentlyai/evidently/assets/40850370/748607ea-f69e-4de3-8193-42eb0fdb87ce)

```
TestSuite(
    tests: Optional[List[Union[evidently.tests.base_test.Test, evidently.test_preset.test_preset.TestPreset, evidently.utils.generators.BaseGenerator]]],
    options: Union[evidently.options.base.Options, dict, List[evidently.options.option.Option], NoneType] = None,
    timestamp: Optional[datetime.datetime] = None,
    id: Optional[uuid.UUID] = None,
    metadata: Dict[str, Union[str, Dict[str, str], List[str]]] = None,
    tags: List[str] = None,
)
```

**Usecase:** 
1. Lets say we want to create one testsuit with same metric but with different parameters being used and based on those we want to drive the retraining etc. Although we can create different TestSuits but again we want to combine results in same response.

**Comment by mike0sv** [comment]
In general this should be possible, but in this case our de-duplication algorithm thinks it's the same metric, even with different parameters. I will take a look

**Comment by ketangangal** [comment]
Thanks !
