### ISSUE TITLE
Discord link does not work

### ISSUE THREAD

**Issue by burkovae** [evidentlyai/evidently#72]
It seems that https://discord.gg/xZjKRaNp8b has expired. Are you still maintain a discord community?

**Comment by elenasamuylova** [comment]
Hi @burkovae ! Yes, the community is indeed active. I am testing the link and it works on my side and is set to never expire. While we drill down to the core, can you try this temporary link as an alternative? https://discord.gg/tCRgAbny

**Comment by burkovae** [comment]
That's totally strange!

![image](https://user-images.githubusercontent.com/15078122/140448607-2e9ddd26-a99d-45e4-bb9c-83601cd397b6.png)

It tells me, that I have no permission to join.

**Comment by burkovae** [comment]
And now I tested it from another (private) PC and it worked.

**Comment by burkovae** [comment]
Okay, sorry, it was some strange cache invalidation on my part.

**Comment by elenasamuylova** [comment]
@burkovae great that it is solved!
