### ISSUE TITLE
Evidently 0.3 is compatible with DVC 3, but Evidently 0.4 is not

### ISSUE THREAD

**Issue by jlopezpena** [evidentlyai/evidently#722]
Output from trying to solve the dependencies (using `poetry`):

```
Because no versions of evidently match >0.4.0,<0.4.1 || >0.4.1,<0.5.0
 and evidently (0.4.0) depends on iterative-telemetry (0.0.5), evidently (>=0.4.0,<0.4.1 || >0.4.1,<0.5.0) requires iterative-telemetry (0.0.5).
    And because evidently (0.4.1) depends on iterative-telemetry (0.0.5), evidently (>=0.4.0,<0.5.0) requires iterative-telemetry (0.0.5).
    And because dvc (>=3,<4) requires iterative-telemetry (>=0.0.7) (1), dvc (>=3,<4) is incompatible with evidently (>=0.4.0,<0.5.0)
```

Could be solved by relaxing the dependency on `iterative-telemetry` on Evidently's side. 
Happy to open a PR if you ok with the change!

**Comment by mike0sv** [comment]
That is exactly what I have found out! You can actually just change it to `>=0.0.5`, in this case in py37 env 0.0.5 will be installed and in other envs latest will be used. Can you create a PR with this?
