### ISSUE TITLE
pydantic version upper bound

### ISSUE THREAD

**Issue by anh-le-profinit** [evidentlyai/evidently#724]
Hello, 

is there a reason for capping _pydantic_ at <2? 
I'd like to use some of _pydantic_ 2.x features such as  `computed_field` or `model_validator` which is not currently possible in conjunction with Evidently.

Thank you.

**Comment by mike0sv** [comment]
Pydantic v2 is almost full re-write, so there are many incompatible stuff. We put this restriction before it's release in case something breaks. I will investigate if we can loosen the restriction without breaking anything (but I highly doubt it). At some point we will migrate to pydantic v2 though

**Comment by anh-le-profinit** [comment]
Thanks, I'm aware that currently Pydantic v2 isn't quite compatible with Evidently. 
Hope the changes would not be extensive and the adoption as seamless as possible.

**Comment by mike0sv** [comment]
I just tried updating to v2 and its definitely will not be a walk in the park :(

**Comment by amotzop** [comment]
It seems to me that after #792 it now should be possible to remove the `pydantic<2` capping, so evidently can be used together with other libraries that do use it
