### ISSUE TITLE
Normalize volume of drift reports

### ISSUE THREAD

**Issue by VaishnaviMendhe** [evidentlyai/evidently#732]
As volume of current and reference data is always gonna be different, need to customize the preset such that, plot uses different y-scale for reference and current data. 
Tried creating a custom metric for drift reports, but there is not much information regarding how to implement plotly in the code.
Also why evidently is only using bar graphs, i would like to plot histogram
![image](https://github.com/evidentlyai/evidently/assets/124362800/8564ec72-fcdd-4d11-a9f1-29dc117d7363)
trying to create plots like this.

**Comment by elenasamuylova** [comment]
Hi @VaishnaviMendhe, 

You can use the "percentage" switch on the plot to switch from absolute values to % - this will help align the distributions when the reference and current datasets have different sizes. Basically, you can switch from:

Absolute values:
![](https://user-images.githubusercontent.com/67064421/259807679-6f7045cf-fcb1-4b32-aa7d-eaa3e4f402dc.png)

To percentage values:
![](https://user-images.githubusercontent.com/67064421/259807773-fc67dd34-dd48-4059-94db-ead494dfedd4.png)

Evidently, a bar chart represents a distribution, so it works like a histogram but is faster. 

If you do not see this switch "button" on your plots, make sure you are using the latest Evidently version.

Does this solve an issue for you?

**Comment by VaishnaviMendhe** [comment]
Thats awesome, Thanks @elenasamuylova 

Updating evidently version will resolve my problem, hope this won't break anything else.

**Comment by dehiker** [comment]
Hi @elenasamuylova , could I set the data distribution default to "percentage"? Thanks a lot!

**Comment by elenasamuylova** [comment]
Hi @dehiker - there is no such parameter, I am afraid. Both visualizations are always available, and you can manually switch between them when viewing the plots.
