### ISSUE TITLE
Different bins for reference and current distribution and minor ideas 

### ISSUE THREAD

**Issue by davidbange** [evidentlyai/evidently#74]
hey I saw your presentation at pydata global and really appreciate your work and played around with the data-drift report a little.

1) My main problem is, that different bins are used for reference an current distribiton, so i find the diagrams somewhat misleading
![image](https://user-images.githubusercontent.com/69851777/141085546-900eba8e-0887-4b81-ba4e-7b23a803fada.PNG)

![image](https://user-images.githubusercontent.com/69851777/141085802-2fbc67ef-09b6-45ec-b6a6-07c8f1bc33f2.png)

2) is there a way to disable the data drift plot at all? because in my case with a lot of data points with high deviation this plot takes a lot of memory/performance but is rarly useful

3) what i would find useful is a quick overview of the means and standard deviations in the overview of all features, maybe this could be added as a feature :)

And again thank you for your work. This really helps me a lot since i only tracked shifts in the means in the past.

**Comment by emeli-dral** [comment]
Hi @davidbange 
Thank you for sharing your thoughts! We really appreciate! 
Let me try to comment a bit.
 
1. Yep, there is a problem indeed. Now we calculate bins for reference and current datasets separately, and we are considering different approaches.
What do you think will be the best option? Do you think we should reuse bins from reference dataset for current data also? Or may be something else?

2. Currently there is no easy way to include or exclude specific widgets in the reports for the moment. Now the only way is to make it at the code level: explicitly remove the instructions for distributions plotting from ```class DataDriftTableWidget(Widget)``` in https://github.com/evidentlyai/evidently/blob/main/evidently/widgets/data_drift_table_widget.py. And then rebuild the project to use it locally. 
Also, we are releasing soon the ability to parametrise Tabs and Dashboards, and an option to switch on/switch off widgets will be there 😎 

3. Indeed! It will be included in our next report: we designing somewhat like dataset overview report! Good to know that it seems interesting 🙂

**Comment by emeli-dral** [comment]
1.  Won't be fixed (although it is partially updated, the order of the bins if fixed now)
2. The option to enable/disable the data drift plots will we implemented for TestSuites
3. The overview of the means and standard deviations of all features is implemented in the DataQualityTab() of Dashboards
here is the example: https://github.com/evidentlyai/evidently/blob/main/examples/sample_notebooks/data_quality_bike_sharing_demand.ipynb
