### ISSUE TITLE
Issue with importing Dashboard after latest release 0.1.28.dev0 ?

### ISSUE THREAD

**Issue by Neel-Renavikar** [evidentlyai/evidently#75]
I am exploring evidently and I am new to the tool. I was trying to use it on google colab. It worked fine until today, but when I tried using it today the following import statement started throwing error. 

'from evidently.dashboard import Dashboard'

The error is : 
![image](https://user-images.githubusercontent.com/13672259/141222833-5b5910da-d96a-4567-9465-d6bb84c761d0.png)
 
When I revert to the older version using "pip install evidently==0.1.27.dev0" , the import works well again. 
Has the new version stopped supporting any particular python version?

**Comment by emeli-dral** [comment]
Hi @Neel-Renavikar 

thank you for reporting this! 
We do some experiments with testing design, and we lost tests for python < 3.8 by mistake. 

Fixing the 🐞!

**Comment by emeli-dral** [comment]
fixed in ```0.1.29.dev``` version
