### ISSUE TITLE
Index of dataframe must be called "index"

### ISSUE THREAD

**Issue by JulienfLeBoucher** [evidentlyai/evidently#773]
Hi, 

This is my first issue submission. Sorry by advance if does not meet the requirements.

I've been using evidently for the first time and I got an error while providing dataframes with an index named differently than 'index'.

It can be witnessed in [this notebook](https://nbviewer.org/github/JulienfLeBoucher/OC_MLOps_credit_scoring/blob/main/data_drift/data_drift.ipynb) in the 4th section called 'data drift on main features'.

I have let the error on purpose so you can see the traceback there.

The problem comes from evidently/utils/visualizations.py line 1225 assuming that after reset_index() the index would be named 'index' which was False in my case.

I do not know if fix suggestions are welcome or not, but if so, may be one could extend the Column_mapping() with the index name and use it in replacement of 'index' in the problematic line, or preprocess dataframe ensuring the index name is 'index'.

Thanks for reading me.

**Comment by emeli-dral** [comment]
Hi @JulienfLeBoucher ,
Thank you for rising the issue and for fix suggestion! It is very welcomed :) 

Could you please clarify the version of evidently you used?

**Comment by JulienfLeBoucher** [comment]
Great!

pip freeze gives : 
evidently @ git+https://github.com/evidentlyai/evidently.git@0f9496e1aa817addaa4d86cb22515bd0f54e0ee6

**Comment by emeli-dral** [comment]
@0lgaF could you please help with that?

**Comment by emeli-dral** [comment]
Hi @JulienfLeBoucher , we merged the fix recently! If you use evidently from the source code it is already available in the main branch. The fix will be included in the next release as well.

**Comment by JulienfLeBoucher** [comment]
Ty!
