### ISSUE TITLE
Support for tags and metadata in the UI

### ISSUE THREAD

**Issue by emeli-dral** [evidentlyai/evidently#779]
Users can specify tags and metadata for snapshots. See the [docs](https://docs.evidentlyai.com/user-guide/monitoring/snapshots#add-tags) for more details.

This data then goes to the snapshot json and is accessible via API in the UI service.
The task is to let users see those tags and metadata in the UI and filter & order snapshots by tags and metadata. This functionality should be supported in Reports and Test Suites tabs in the UI.

Here is a support picture to illustrate the idea:

![Image](https://github.com/evidentlyai/evidently/assets/22995068/90cc38f8-8c00-4707-88f0-1effae2ce5e8)

**Comment by DimaAmega** [comment]
Blocked by #786

**Comment by DimaAmega** [comment]
How we should display metadata?

* All collapsed by default? (no on screenshot below)
* What about colors? (see screenshot)
 

![Image](https://github.com/evidentlyai/evidently/assets/32310771/38b27ae4-fc7b-4f94-8f9e-2797c7db91a9)

@emeli-dral ^^

**Comment by DimaAmega** [comment]
This color theme better i believe



![Image](https://github.com/evidentlyai/evidently/assets/32310771/f109b9f8-11be-472e-b891-8568f74d3658)

**Comment by DimaAmega** [comment]
With @mou we deployed it here
https://github.com/evidentlyai/cloud_service/pull/175

But there is no projects and i don't know why

@mike0sv @emeli-dral FYI

**Comment by DimaAmega** [comment]
Wait for proper deploy

**Comment by DimaAmega** [comment]
- [X]  Tags (finished by #798 )
- [X] Metadata (basics) #873
