### ISSUE TITLE
Update the Bike Demand Forecasting notebook

### ISSUE THREAD

**Issue by elenasamuylova** [evidentlyai/evidently#781]
**Description:**

Update the Bike Demand Forecasting notebook example adding the `"render": {"raw_data": True} option` to all the Reports.

**Context:**

A blog tutorial https://www.evidentlyai.com/blog/tutorial-1-model-analytics-in-production shows an example of using an Evidently Regression Performance report. 

Here is the accompanying code example:
https://github.com/evidentlyai/evidently/blob/main/examples/data_stories/bicycle_demand_monitoring.ipynb 

Since creating this blog, we updated the Evidently Reports, introducing raw data aggregation that is now applicable by default. Because of this, the visuals you get when running the example do not match the ones in the blog. To get the visuals that match the ones in the blog, users need to turn the `raw_data` option. 

**Implementation:**

Edit the notebook, adding the `raw_data` option https://github.com/evidentlyai/evidently/blob/main/examples/data_stories/bicycle_demand_monitoring.ipynb to all generated Reports.

Follow the documentation on using the raw data option https://docs.evidentlyai.com/user-guide/customization/report-data-aggregation.

**Comment by anirudhsudhir** [comment]
I'd like to work on this issue. Could you assign it to me?
