### ISSUE TITLE
Update the sample "Metrics" notebook

### ISSUE THREAD

**Issue by elenasamuylova** [evidentlyai/evidently#783]
**Description:**

Update the sample notebook showing how to use Metrics with` "render": {"raw_data": True}` option.

**Context:**

Evidently documentation includes a sample notebook that shows all Metrics for tabular data.
https://github.com/evidentlyai/evidently/blob/main/examples/sample_notebooks/evidently_metrics.ipynb

By default, all Evidently Reports show aggregated visuals. However, there is an option to include raw data in the Reports, generating different (non-aggregated) visualizations.

We want to add an example of using this functionality to the example notebook.

**Implementation:**

Edit the notebook, adding an example using the `raw_data` option for a couple of Metrics - for example, create a simple Report with  `ColumnDriftMetric` and  `ColumnValuePlot` Metrics. https://github.com/evidentlyai/evidently/blob/main/examples/sample_notebooks/evidently_metrics.ipynb 

Add a new header under "How to set metric parameters?" - for example, "How to use Metrics with raw data?"

Follow the documentation on using the raw data option https://docs.evidentlyai.com/user-guide/customization/report-data-aggregation.

**Comment by anirudhsudhir** [comment]
I'd like to work on this issue. Could you assign it to me?
