### ISSUE TITLE
Change the display name for DatasetCorrelationsMetric()

### ISSUE THREAD

**Issue by elenasamuylova** [evidentlyai/evidently#784]
**Description:**

Change the the display name for` DatasetCorrelationsMetric()`. Instead of "Dataset Correlations Metric", it should simply have "Dataset Correlations" in the title.

<img width="1283" alt="Screenshot 2023-09-29 at 03 52 04" src="https://github.com/evidentlyai/evidently/assets/67064421/8c2826e3-02cc-499c-ad03-b048a9aa14f0">

**Comment by Dv04** [comment]
Hello, can I get assigned to this issue now? As this is for the Hacktoberfest, I will submit the PR as soon as it starts.

**Comment by Dv04** [comment]
Hey @elenasamuylova, Just asking if I can be assigned or if should I create a PR.

**Comment by elenasamuylova** [comment]
Hi @Dv04, we do not assign issues directly - but feel free to leave a comment here that you are working on it and send the PR; we will review them on a first-come basis!  

The screenshot you shared looks good!

**Comment by Dv04** [comment]
Hey @elenasamuylova, Thanks. Yes I will be working on this issue and submit it as soon as possible.

**Comment by Dv04** [comment]
Hey @elenasamuylova, in which branch do I have to merge the issue, as it is blocking me from doing it in the base branch.

**Comment by Diksha-3905** [comment]
Hi, I’d love to work on this—can I take it
