### ISSUE TITLE
Fix docs and example on classification column mapping

### ISSUE THREAD

**Issue by elenasamuylova** [evidentlyai/evidently#800]
**Description:**

There is an error on the docs page regarding column mapping for binary probabilistic classification https://docs.evidentlyai.com/user-guide/input-data/column-mapping#binary-probabilistic-classification-option-1

There is the same error for all 3 options. For example, instead of:

```
column_mapping = ColumnMapping()
column_mapping.target = 'target'
column_mapping.prediction = 'prediction'
pos_label = 1
column_mapping.target_names = ['churn', 'not_churn']
```

We should specify that `pos_label` is passed inside `column_mapping`:

```
column_mapping = ColumnMapping()
column_mapping.target = 'target'
column_mapping.prediction = 'prediction'
column_mapping.pos_label = 1
column_mapping.target_names = ['churn', 'not_churn']
```

This error duplicates in the how-to example notebook: 
https://github.com/elenasamuylova/evidently/blob/main/examples/how_to_questions/how_to_use_column_mapping.ipynb

Related: https://github.com/evidentlyai/evidently/issues/799

**Implementation**

Fix the error:
- Update the docs markdown page https://github.com/evidentlyai/evidently/blob/main/docs/book/input-data/column-mapping.md
- Update the how-to example notebook https://github.com/elenasamuylova/evidently/blob/main/examples/how_to_questions/how_to_use_column_mapping.ipynb

**Comment by elenasamuylova** [comment]
Hi @ujwalkumar1995, since it is a small issue - we do not directly assign them, but you are free to submit the PR. We'll review them on a first-come basis.

**Comment by ujwalkumar1995** [comment]
> Hi @ujwalkumar1995, since it is a small issue - we do not directly assign them, but you are free to submit the PR. We'll review them on a first-come basis.

Hey @elenasamuylova 
Sure. Have submitted a PR. Kindly review and let me know in case of any feedback.
