### ISSUE TITLE
Reports can only be saved to a file path instead of a handle.

### ISSUE THREAD

**Issue by thomasniebler** [evidentlyai/evidently#851]
If calling `save_html` (see https://github.com/evidentlyai/evidently/blob/main/src/evidently/suite/base_suite.py#L182C25-L182C33), it only allows to provide a file name as parameter.

However, for saving it to S3 or writing the stream somewhere else, it would be nice to obtain a handle that supports `write`.

**Comment by mike0sv** [comment]
Hi @thomasniebler . You can try `report.get_html()`. You can just pass the result to your `stream.write()` method

**Comment by thomasniebler** [comment]
Still, would you mind adding a PR to allow passing a stream instead of a file handle?

**Comment by emeli-dral** [comment]
Hey @thomasniebler , we just supported s3 for ```save_html``` method. It is not released in the package yet, but you can check it out in the main branch.
We would love to get your feedback.

**Comment by thomasniebler** [comment]
Hi @emeli-dral, the inclusion of an IO type seems like a clever way to solve this issue, thank you! :)
