### ISSUE TITLE
TypeError: analyzers() missing 1 required positional argument: 'self'

### ISSUE THREAD

**Issue by TawabG** [evidentlyai/evidently#86]
I am interested in the historical drift visualization tutorial. However, after downloading the notebook and running all cells, I encountered an error at cell 200: "TypeError: analyzers() missing 1 required positional argument: 'self'"

Source: https://github.com/evidentlyai/evidently/blob/main/evidently/tutorials/historical_drift_visualization.ipynb

**Comment by emeli-dral** [comment]
Hi @TawabG ,
thank you for pointing this out!

Here is a fix: https://github.com/evidentlyai/evidently/blob/main/evidently/tutorials/historical_drift_visualization.ipynb

**Comment by TawabG** [comment]
Hey @emeli-dral, thanks for the quick reply! It's fixed! Thank you😃
