### ISSUE TITLE
How to set custom target feature name ?

### ISSUE THREAD

**Issue by snassimr** [evidentlyai/evidently#867]
It's pretty annoying to rename my target to "target" each time .

Anyway to pass custom target feature name ?

My snippet : 

``
from evidently.test_suite import TestSuite
from evidently.test_preset import BinaryClassificationTestPreset
from evidently.tests import *

rename_dict = {
    "class" : "target"
}

reference_data_dp.rename(columns=rename_dict, inplace=True)
prod_data_dp.rename(columns=rename_dict, inplace=True)

model_performance_suite = TestSuite(tests=[BinaryClassificationTestPreset()])
``

**Comment by elenasamuylova** [comment]
Hi @snassimr, you can use column mapping as shown here: https://docs.evidentlyai.com/user-guide/input-data/column-mapping.

**Comment by snassimr** [comment]
Hi ,

I am trying to use 

model_performance_suite.run(reference_data=reference_data_dp, current_data=prod_data_dp, column_mapping=column_mapping)

But model_performance_suite returned is None

**Comment by elenasamuylova** [comment]
@snassimr Could you share how you define the column mapping object?

**Comment by elenasamuylova** [comment]
You can use this reference example with different ways to map your columns for classification: https://github.com/elenasamuylova/evidently/blob/main/examples/how_to_questions/how_to_use_column_mapping.ipynb

**Comment by snassimr** [comment]
Yep . The second link helped to understand that the error on my side
