### ISSUE TITLE
Export Evidently Reports and Tests to flat tables/dataframes

### ISSUE THREAD

**Issue by mederic-hurier-partner** [evidentlyai/evidently#901]
Hello,

We plan to integrate Evidently to our data platform (pandas, spark, data lake, ...), and we'd appreciate to export data from reports/tests as flat tables (e.g., dataframes) instead of nested structures (e.g., dicts).

For instance, we want to export data from `metrics.DataDriftTable` as follow:

```python
evidently_report = Report(
    metrics=[metrics.DataDriftTable()],
)
evidently_report.run(
    current_data=current,
    reference_data=reference,
    column_mapping=evidently_column_mapping,
)
# result
records = evidently_report.as_dict()
result = records["metrics"][0]["result"]
drifts = result["drift_by_columns"]
# evaluation
evaluation = pd.DataFrame(drifts.values())
evaluation = evaluation.drop(columns=["current", "reference"])
```

We would love to export the results by simply using `report.as_dataframe()` (to be agnostic of pandas, spark, or other frameworks like polars).

You may also consider the upcoming Dataframe API: https://data-apis.org/dataframe-api/draft/index.html.

**Comment by emeli-dral** [comment]
Hi @mederic-hurier-partner ,
Thank you so much for raising this up!

We previously had an attempt to implement this and it looks like the time has come :) 

There are two issues with transforming the report into a flat table:
1. There is no universally good way to understand which dataframe is desired for each metric. Additionally, different users may need dataframes of different structures.
2. The second problem is that it is unclear how to merge dataframes from different metrics in one report into a single dataframes. On the one hand, metrics can be completely different with various fields, and on the other hand, they can be identical (for example, from generators - many identical metrics calculated for different columns), and in this case, merging is desired.

So, tanking this into account we propose the following approach:

1. Firstly, we will implement a not-so-elegant but universal way to create a dataframe by simply flattening the metric into a series with complex keys.
2. We will also implement a mechanism to override this logic and redefine the transformation methods into a dataframe for several important metrics. In particular, we will use what you have extended for the DataDriftTable as a reference.

After this, we will be able to accept PRs for redefining the dataframe format for metrics that you use :)
How does it sound?

**Comment by emeli-dral** [comment]
Hi @mederic-hurier-partner!

We polishing up ``as_pandas`` implementation here #966 
We already have a nice pandas renderer for ```DataDriftTable``` metric, feel free to check it out in feature/as_dataframe branch. We would love to know you opinion :)
