### ISSUE TITLE
Ranking metric coverage under PopularityBias doesn't use k parameter

### ISSUE THREAD

**Issue by soogui** [evidentlyai/evidently#945]
Hi!
Recently I decided to adopt Evidently to automate reporting around a recommender model, focusing on ranking metrics first.

I believe there might the a problem with the implementation of coverage under `PopularityBias` metric. The formula present in the [docs](https://docs.evidentlyai.com/reference/all-metrics/ranking-metrics#id-2.-coverage) includes the K parameter:
Coverage = Number of unique items recommended@K / Total number of unique items

However, the value of the coverage returned by the `Report` does not change upon varying k (5, 10, etc.). I also checked the source and [the calculation does not include k parameter](https://github.com/evidentlyai/evidently/blob/ccade89689a6b9f9afbe46fbd8589ecc083477d3/src/evidently/metrics/recsys/popularity_bias.py#L121).
 
This looks like a bug to me, but would like some confirmation whether this is the intended behaviour or not. If it is indeed a bug I would be happy to contribute with a fix.

Thank you for the amazing project!

**Comment by elenasamuylova** [comment]
Hi @soogui , thanks for reporting this - it does indeed look like an omission. Would you like to send a pull request with a fix?

**Comment by soogui** [comment]
Sure, I would be happy to contribute!

**Comment by sky-2002** [comment]
Hey @soogui , are you still working on this? Let me know, if not, I can take this up.

**Comment by soogui** [comment]
@sky-2002 Thanks for checking in! I plan to work on this in the next few days.
