### ISSUE TITLE
Classification Report: Handle time series data??

### ISSUE THREAD

**Issue by benja20029** [evidentlyai/evidently#967]
Hi, i hope you're doing well :)!

I wanted to know, there's any feature/preset that could help me to make a plot like this but grouping by timestamp??
<img width="1243" alt="image" src="https://github.com/evidentlyai/evidently/assets/81534737/c123cef3-5ed2-4df4-8786-3e5ad2b558ab">

In order to see if i should re train the model or not, i would really like to see if the accuracy decreases through time.

Thanks in advance!

**Comment by elenasamuylova** [comment]
Hi @benja20029, a Report shows the performance for a particular batch of data. If you want to monitor the model quality over time, you can consider generating such Reports on a cadence (e.g. daily, weekly, etc) and then launching the ML monitoring dashboard that allows building time series plots from individual snapshots. Here is the quickstart for self-hosting: https://docs.evidentlyai.com/get-started/tutorial-monitoring

You can also consider implementing a custom metric with its render for the Report to add a plot showing the chosen quality metric over time. However, this requires familiarity with Plotly. Here is the guide for the custom metric: https://github.com/evidentlyai/evidently/blob/main/examples/how_to_questions/how_to_make_custom_metric_and_test.ipynb

**Comment by benja20029** [comment]
I will try the first option then, thanks!

There's any way of generating the dashboard as files that doesn't need to be running in the terminal and instead works with a lambda function or a cron job (for example)??

**Comment by elenasamuylova** [comment]
@benja20029 to create the Reports, you can run a cron job (or orchestrate it however you like - e.g. using a tool like Airflow etc.) This will result in a JSON snapshot (that describes the model performance for a specific period in your case) in a chosen directory. But the ML monitoring dashboard is a service (that reads JSONs from the directory), so you need to run it from the Terminal to launch. 

There is also a hosted commercial version (Evidently Cloud, which is currently in private beta https://docs.evidentlyai.com/get-started/tutorial-cloud) if you do not want to self-host the ML monitoring dashboard.

**Comment by benja20029** [comment]
I understand, thanks!
