### ISSUE TITLE
evidently 0.4.15 depends on pydantic<2

### ISSUE THREAD

**Issue by ThiagoZLC** [evidentlyai/evidently#989]
Hi, I'm currently in a project that uses airflow 2.8.0 which depends on the pydantic version>=2.3.0.

Is there a version of evidently that uses pymantic>2? Or are there plans to update the project?

Thanks!

**Comment by elenasamuylova** [comment]
Hi @ThiagoZLC, here is a related issue: https://github.com/evidentlyai/evidently/issues/862 

The Evidently UI service depends on FastAPI - this prevents us from simply bumping the `pydantic` version. We are working on addressing this by replacing FastAPI dependency for `litestar`.

**Comment by emeli-dral** [comment]
solved in version 0.4.16
