### ISSUE TITLE
BUG: unable to disable telemetry through environment variables

### ISSUE THREAD

**Issue by carlsonp** [evidentlyai/evidently#996]
The [documentation](https://docs.evidentlyai.com/support/telemetry) suggests using an environment variable to disable telemetry.  Normally I would leave it on but it's being blocked by our corporate networking.

I am deploying evidently (`0.4.15`) via a Docker container.  I've tried both setting the environment variable in the `Dockerfile`

```
# https://docs.evidentlyai.com/support/telemetry
# turn off tracking
ENV DO_NOT_TRACK=1
```

As well as within a startup script

```
#!/bin/bash
# startup.sh
export DO_NOT_TRACK=1
evidently ui
```

I can `docker exec` into the container and run `env` and I see the environment variable set.

The logic in `src/evidently/telemetry.py` looks correct.  I'm not sure where else to look but it seems broken to me.

**Comment by emeli-dral** [comment]
Hey @carlsonp ,
working on it.

cc @mike0sv
